function campDetail(id){const a=(S.myCamps||[]).find(x=>String(x.id)===String(id));if(!a)return;const ch=(a.channels||[]).map(c=>`${esc(c.name)} · ${c.product||''}${c.price?' '+c.price+'만':''}`).join("<br>")||"-";const row=(k,v)=>`<div class="py-2 border-b border-g100 last:border-0"><p class="text-[13px] text-g400 mb-0.5">${k}</p><div class="text-[15px] text-g800 break-all">${v||'-'}</div></div>`;modal(`<div class="flex items-center justify-between mb-3"><h3 class="text-[19px] font-bold text-g900 break-all">${esc(a.brand_name)} 신청내용</h3><button onclick="closeModal()" class="w-8 h-8 rounded-full bg-g100 grid place-items-center text-g500 flex-shrink-0">✕</button></div><div class="max-h-[60vh] overflow-y-auto">${row("상태",statusBadge(a.status))}${row("업로드 희망일",esc(a.preferred_date||''))}${row("제품 링크",a.product_link?`<a href="${esc(a.product_link)}" target="_blank" class="text-blue underline">${esc(a.product_link)}</a>`:'-')}${row("희망 채널",ch)}${row("활용 소재",esc(a.material||''))}${row("광고 고지 방식",esc(a.ad_disclosure||''))}${row("희망 영상 컨셉",esc(a.concept||''))}${row("요청사항",esc(a.note||''))}${row("금액 (VAT 별도)",`<span class="font-bold text-blue num">${wonM(a.total_amount||0)}</span>`)}</div><div class="flex gap-2 mt-4"><button onclick="setActiveCamp('${a.id}');closeModal();go('workflow')" class="${BTN} flex-1">워크플로우 진행 →</button><button onclick="closeModal()" class="${BTN_GHOST} px-5">닫기</button></div>`);}
function renderMyCamps(){const el=document.getElementById("myCampWrap");if(!el)return;const cs=S.myCamps||[];if(!cs.length){el.innerHTML='<div class="text-[15px] text-g400 text-center py-8">아직 신청한 캠페인이 없습니다.<br>상단 ‘캠페인 추가 신청’으로 시작하세요.</div>';return;}
el.innerHTML=cs.map(a=>{const on=S.activeCamp&&String(S.activeCamp.id)===String(a.id);return `<div onclick="setActiveCamp('${a.id}')" class="border ${on?'border-blue bg-blue-soft':'border-g100'} rounded-[20px] p-4 flex items-center gap-3 flex-wrap cursor-pointer hover:border-blue/50"><div class="flex-1 min-w-0"><div class="flex items-center gap-2"><p class="font-bold text-g900 text-[16px] truncate">${esc(a.brand_name)}</p>${statusBadge(a.status)}${on?'<span class="text-[11px] font-bold text-blue">선택됨</span>':''}</div><p class="text-[13px] text-g500 mt-1 truncate">${(a.channels||[]).map(c=>c.name).join(", ")||"채널 미선택"}</p></div><div class="text-right flex-shrink-0"><p class="text-[16px] font-bold text-blue num">${wonM(a.total_amount||0)}</p><button onclick="event.stopPropagation();campDetail('${a.id}')" class="text-[12px] text-g500 font-bold underline">신청내용</button></div></div>`;}).join("");if(window.lucide)lucide.createIcons();}
function viewCustomerDashboard(){setTimeout(loadMyCamps,30);const c=S.activeCamp;const wf=c?wfOf(c):{step:1};const cur=Math.min(wf.step,7);const bn=(S.cust&&S.cust.brand)?S.cust.brand:"고객";const pct=Math.round(Math.min(cur,7)/7*100);
const todoMap={1:["승인 후 진행됩니다"],2:["소재·가이드 파일 업로드 후 제출"],3:["크놀AD 콘티 작성 대기"],4:["전달된 콘티 컨펌 또는 수정 요청"],5:["크놀AD 영상 제작 대기"],6:["전달된 영상 컨펌 또는 수정 요청"],7:["리포트에서 업로드·성과 확인","결제(정산) 진행"]};
const todo=todoMap[cur]||["진행 대기 중"];
const stageLabel=cur>=7?"완료 · 리포트 단계":(WF[cur-1]?WF[cur-1].t:"대기");
const steps=WF.map((st,i)=>{const idx=i+1;const done=idx<cur,act=idx===cur;return `<div class="flex items-center gap-3 px-3 py-2.5 rounded-2xl ${act?'bg-blue-tint':''}"><div class="w-6 h-6 rounded-full grid place-items-center flex-shrink-0 text-[12px] font-bold ${done?'bg-emerald-500 text-white':act?'bg-blue text-white':'bg-g200 text-g500'}">${done?'<i data-lucide="check" class="w-3 h-3"></i>':idx}</div><span class="text-[15px] flex-1 ${done?'text-g400 line-through':act?'text-g900 font-bold':'text-g500'}">${st.t}</span>${done?'<span class="text-[13px] text-emerald-600 font-bold">완료</span>':act?'<span class="text-[13px] text-blue font-bold">진행중</span>':'<span class="text-[13px] text-g300">대기</span>'}</div>`;}).join("");
return `<div class="p-8 md:p-10">${pageHeader("CAMPAIGN","캠페인 관리",esc(bn)+" 님의 캠페인 현황입니다. 캠페인을 누르면 신청 내용을 볼 수 있어요.")}
<div class="grid lg:grid-cols-3 gap-4 mb-4"><div class="${CARD} lg:col-span-2 p-7"><div class="flex items-center justify-between mb-4"><h2 class="text-[18px] font-bold text-g900">내 캠페인</h2><button onclick="newApply()" class="text-[14px] text-blue font-bold inline-flex items-center gap-1"><i data-lucide="plus" class="w-4 h-4"></i>캠페인 추가 신청</button></div><div id="myCampWrap" class="space-y-2"><div class="text-g400 text-center py-8 text-[15px]">불러오는 중…</div></div></div>
<div class="${CARD} p-7 flex flex-col items-center justify-center text-center"><p class="text-[14px] text-g400 mb-1">진행 단계</p><div class="font-display text-[48px] font-bold text-g900 num leading-none">${Math.min(cur,6)}<span class="text-[24px] text-g300">/6</span></div><p class="text-[13px] text-g500 mb-3">${esc(stageLabel)}</p><div class="w-full bg-g100 rounded-full h-2 mb-3"><div class="bg-blue h-2 rounded-full transition-all" style="width:${pct}%"></div></div><button onclick="go('workflow')" class="text-[15px] text-blue font-bold">워크플로우 진행하기 →</button></div></div>
<div class="grid lg:grid-cols-2 gap-4"><div class="${CARD} p-7"><h2 class="text-[16px] font-bold text-g900 mb-4">진행 단계</h2><div class="space-y-0.5">${steps}</div></div><div class="${CARD} p-7"><h2 class="text-[16px] font-bold text-g900 mb-3">현재 할 일</h2>${todo.map(it=>`<div class="flex items-center gap-3 py-1.5"><div class="w-2 h-2 rounded-full bg-blue flex-shrink-0"></div><span class="text-[16px] text-g700">${it}</span></div>`).join("")}<button onclick="go('workflow')" class="${BTN} w-full mt-4 py-3">워크플로우에서 처리하기</button></div></div></div>`;}
function viewMyPage(){setTimeout(loadMyCamps,30);const c=S.cust||{};const a=S.activeCamp||(S.myCamps&&S.myCamps[0])||{};const kv=(k,v)=>`<div class="flex justify-between py-2 border-b border-g100 last:border-0"><span class="text-g500 text-[15px]">${k}</span><span class="font-bold text-g900 text-[15px] text-right break-all">${esc(v||'-')}</span></div>`;
return `<div class="p-8 md:p-10"><div class="max-w-2xl">${pageHeader("MY PAGE","마이페이지","신청 정보 기준으로 생성된 내 정보입니다")}
<div class="${CARD} p-7 mb-4"><h2 class="text-[16px] font-bold text-g900 mb-3">내 정보</h2>${kv("담당자",c.name||a.contact_name)}${kv("아이디(이메일)",c.email||a.email)}${kv("연락처",a.phone)}${kv("회사/브랜드",c.brand||a.brand_name)}</div>
<div class="${CARD} p-7 mb-4"><h2 class="text-[16px] font-bold text-g900 mb-3">최근 신청 정보</h2>${kv("업로드 희망일",a.preferred_date)}${kv("희망 채널",(a.channels||[]).map(x=>x.name).join(", "))}${kv("활용 소재",a.material)}${kv("광고 고지 방식",a.ad_disclosure)}${kv("금액 (VAT 별도)",wonM(a.total_amount||0))}</div>
<div class="${CARD} p-7"><h2 class="text-[16px] font-bold text-g900 mb-1">사업자등록증 제출</h2><p class="text-[14px] text-g500 mb-3 leading-relaxed">세금계산서는 <b>크놀AD(에이치알컴퍼니)</b>가 발행합니다. 발행을 위해 사업자등록증을 제출해주세요.</p>${uploadZone("bizFile","사업자등록증 이미지 또는 PDF")}<button onclick="submitBiz()" class="${BTN} w-full mt-3">사업자등록증 제출</button></div>
</div></div>`;}
function submitBiz(){const c=S.activeCamp;if(c){fetch(SUPA_URL+"/rest/v1/knollad_applications?id=eq."+c.id,{method:"PATCH",headers:Object.assign({"Content-Type":"application/json","Prefer":"return=minimal"},SH),body:JSON.stringify({biz_reg:"제출됨"})}).catch(()=>{});}toast("사업자등록증이 제출되었습니다");}
function uploadZone(id,hint){id=id||"fileList";return `<label class="block border-2 border-dashed border-g300 rounded-[20px] p-7 text-center cursor-pointer hover:border-blue hover:bg-blue-soft transition-all"><input type="file" multiple class="hidden" onchange="showFiles(this,'${id}')"><i data-lucide="upload-cloud" class="w-9 h-9 text-g400 mx-auto mb-2"></i><p class="text-[17px] font-bold text-g700">파일을 끌어다 놓거나 클릭해서 업로드</p><p class="text-[14px] text-g400 mt-1">${hint||"제품 이미지·영상·로고·가이드 등 (여러 개 가능)"}</p></label><div id="${id}" class="space-y-2 mt-3"></div>`;}
function showFiles(input,id){const el=document.getElementById(id||"fileList");if(!el)return;const fs=[...input.files];el.innerHTML=fs.map(f=>`<div class="flex items-center gap-2 bg-g50 rounded-2xl px-3 py-2 text-[15px]"><i data-lucide="file" class="w-4 h-4 text-blue flex-shrink-0"></i><span class="flex-1 truncate text-g700">${esc(f.name)}</span><span class="text-g400 text-[12px] num">${(f.size/1024).toFixed(0)}KB</span></div>`).join("");if(window.lucide)lucide.createIcons();if(fs.length)toast(fs.length+"개 파일 선택됨");}
function wfSave(patch){const c=S.activeCamp;if(!c){toast("진행할 캠페인이 없습니다");return;}const wf=Object.assign({},wfOf(c),patch);c.wf=wf;fetch(SUPA_URL+"/rest/v1/knollad_applications?id=eq."+c.id,{method:"PATCH",headers:Object.assign({"Content-Type":"application/json","Prefer":"return=minimal"},SH),body:JSON.stringify({wf})}).then(r=>{if(!r.ok)toast("저장 실패");}).catch(()=>toast("저장 오류"));render();}
function wfDataSubmit(){wfSave({step:3,note:null});toast("자료가 제출되었습니다 · 크놀AD가 콘티를 작성합니다");}
function wfConfirm(){const wf=activeWf();if(wf.step===4)wfSave({step:5});else if(wf.step===6)wfSave({step:7});toast("컨펌되었습니다 · 다음 단계로 진행됩니다");}
function wfReqEdit(){const t=(gv("wfFb")||"").trim();const wf=activeWf();if(wf.step===4)wfSave({step:3,conti:null,note:t});else if(wf.step===6)wfSave({step:5,video:null,note:t});toast("수정 요청이 전달되었습니다 · 크놀AD가 반영 후 재전달합니다");}
function openLink(u){if(!u){toast("링크가 아직 없습니다");return;}window.open(u,"_blank");}
function wfPanel(st){const wf=activeWf();const act=st.act,P='class="mt-4 space-y-3" style="padding-left:52px"';
if(act==="data")return `<div ${P}>${uploadZone("wfData","소재·가이드·레퍼런스 파일")}<input id="wfRef" placeholder="참고 레퍼런스 / 소재 링크 (선택)" class="${INPUT}"><button onclick="wfDataSubmit()" class="${BTN} w-full">자료 제출 완료 →</button></div>`;
if(act==="adminConti"||act==="adminVideo"){const lbl=act==="adminConti"?"콘티":"영상";return `<div ${P}><div class="bg-amber-50 rounded-2xl p-4 text-[15px] text-amber-800 flex items-start gap-3"><i data-lucide="loader-circle" class="w-5 h-5 mt-0.5 flex-shrink-0"></i><span>크놀AD에서 ${lbl}를 제작 중입니다. <b>전달이 완료되어야 다음 단계로 진행</b>할 수 있습니다.</span></div>${wf.note?`<p class="text-[13px] text-g500">최근 수정 요청: ${esc(wf.note)}</p>`:""}</div>`;}
if(act==="conti"||act==="video"){const isC=act==="conti";const lbl=isC?"콘티":"영상 초안";const link=isC?wf.conti:wf.video;if(!link)return `<div ${P}><div class="bg-amber-50 rounded-2xl p-4 text-[15px] text-amber-800 flex items-center gap-3"><i data-lucide="clock" class="w-5 h-5 flex-shrink-0"></i>크놀AD의 ${lbl} 전달을 기다리고 있습니다.</div></div>`;return `<div ${P}><div class="bg-blue-soft rounded-2xl p-4"><p class="font-bold text-g900 mb-1.5">${lbl}가 전달되었습니다</p><button onclick="openLink('${esc(link)}')" class="text-blue font-bold text-[14px] inline-flex items-center gap-1"><i data-lucide="paperclip" class="w-4 h-4"></i>${lbl} 확인하기 ↗</button></div><textarea id="wfFb" rows="2" placeholder="수정 요청 사항을 입력하세요 (선택)" class="${INPUT} resize-none"></textarea><div class="flex gap-2"><button onclick="wfReqEdit()" class="${BTN_GHOST} flex-1">수정 요청</button><button onclick="wfConfirm()" class="${BTN} flex-1">컨펌하고 다음 →</button></div></div>`;}
return "";}
function viewWorkflow(){const c=S.activeCamp;if(!c){setTimeout(loadMyCamps,30);return `<div class="p-8 md:p-10">${pageHeader("WORKFLOW","캠페인 진행")}<div class="${CARD} p-12 text-center text-g500 text-[16px]">승인된 캠페인이 있어야 워크플로우를 진행할 수 있습니다.<br>‘캠페인 관리’에서 캠페인을 선택하세요.</div></div>`;}
const wf=wfOf(c);const cur=wf.step;
const cards=WF.map((st,i)=>{const idx=i+1;const done=idx<cur,act=idx===cur;return `<div class="${CARD} p-5 ${act?'border-2 border-blue':''}"><div class="flex items-center gap-4"><div class="w-9 h-9 rounded-full grid place-items-center flex-shrink-0 font-bold text-[14px] ${done?'bg-emerald-500 text-white':act?'bg-blue text-white':'bg-g100 text-g400'}">${done?'<i data-lucide="check" class="w-4 h-4"></i>':String(idx).padStart(2,"0")}</div><div class="flex-1"><p class="font-bold text-[16px] ${done?'text-g400':act?'text-g900':'text-g400'}">${st.t}</p><p class="text-[13px] text-g400 mt-0.5">${st.d}</p></div><span class="text-[12px] font-bold px-2.5 py-1 rounded-lg ${act?'bg-blue-tint text-blue':done?'bg-emerald-50 text-emerald-600':'bg-g100 text-g400'}">${done?'완료':act?(st.who==='고객'?'내 차례':st.who):st.who}</span></div>${act?wfPanel(st):''}</div>`;}).join("");
const fin=cur>=7;
const doneCard=`<div class="${CARD} p-5 ${fin?'border-2 border-emerald-400':''}"><div class="flex items-center gap-4"><div class="w-9 h-9 rounded-full grid place-items-center flex-shrink-0 font-bold text-[14px] ${fin?'bg-emerald-500 text-white':'bg-g100 text-g400'}">${fin?'<i data-lucide="check" class="w-4 h-4"></i>':'07'}</div><div class="flex-1"><p class="font-bold text-[16px] ${fin?'text-g900':'text-g400'}">업로드 & 인사이트 리포트</p><p class="text-[13px] text-g400 mt-0.5">업로드 URL·썸네일·조회수 등 성과는 <b>리포트</b> 메뉴에서 확인하세요</p></div><span class="text-[12px] font-bold px-2.5 py-1 rounded-lg ${fin?'bg-emerald-50 text-emerald-600':'bg-g100 text-g400'}">${fin?'완료':'대기'}</span></div>${fin?`<div class="mt-4" style="padding-left:52px"><button onclick="go('report')" class="${BTN}"><i data-lucide="bar-chart-3" class="w-4 h-4"></i>리포트에서 영상·인사이트 보기 →</button></div>`:''}</div>`;
const policy=[["콘티 수정","2회까지 무상수정 · 3회차부터 추가요금"],["영상 수정","단순 컷·순서·로고 변경 한정 2회 무상 · 3회차부터 추가요금"],["콘티 변경 발생 시","무상수정 횟수와 관계없이 추가요금 발생"],["제작사 실수로 인한 오류","횟수 제한 없이 무상수정 진행"]];
return `<div class="p-8 md:p-10">${pageHeader("WORKFLOW","캠페인 진행",esc(c.brand_name)+" · 자료 제출·콘티/영상 컨펌까지 홈페이지 안에서 진행됩니다")}
<div class="grid lg:grid-cols-3 gap-5"><div class="lg:col-span-2 space-y-3">${cards}${doneCard}</div>
<div class="${CARD} p-6 self-start lg:sticky lg:top-6"><h2 class="text-[16px] font-bold text-g900 mb-4">수정 정책 및 추가요금</h2><div class="space-y-3">${policy.map(p=>`<div class="pb-3 border-b border-g100 last:border-0 last:pb-0"><p class="font-bold text-[15px] text-g900 mb-1">${p[0]}</p><p class="text-[15px] text-g500 leading-relaxed">${p[1]}</p></div>`).join("")}</div><button onclick="go('settlement')" class="${BTN_GHOST} w-full mt-4 py-3 text-[14px]">결제 / 정산 →</button></div></div></div>`;}
const PAY_ACCOUNT={bank:"국민은행",no:"123456-04-567890",holder:"에이치알컴퍼니(주)"};
function viewSettlement(){const c=S.activeCamp;const wf=c?wfOf(c):{};const amt=c?(c.total_amount||0):0;const won=amt*10000;const vat=won*0.1;const tot=won*1.1;const pay=(c&&c.pay_status)||"미결제";
return `<div class="p-8 md:p-10"><div class="max-w-2xl">${pageHeader("PAYMENT","결제 / 정산","캠페인 대금은 크놀AD(에이치알컴퍼니) 계좌로 입금해주세요")}
<div class="${CARD} p-7 mb-4"><div class="flex items-center justify-between mb-3"><h2 class="text-[16px] font-bold text-g900">결제 금액${c?` · ${esc(c.brand_name)}`:""}</h2>${statusBadge(pay==="결제 완료"?"승인 완료":"검토 대기중")}</div>
<div class="flex justify-between py-2 border-b border-g100"><span class="text-g500">공급가액</span><span class="font-bold num">${wonM(amt)}</span></div>
<div class="flex justify-between py-2 border-b border-g100"><span class="text-g500">VAT 10%</span><span class="num text-g600">${vat.toLocaleString()}원</span></div>
<div class="flex justify-between py-3"><span class="font-bold text-g900">총 결제금액</span><span class="font-bold text-blue text-[18px] num">${tot.toLocaleString()}원</span></div></div>
<div class="${CARD} p-7 mb-4"><h2 class="text-[16px] font-bold text-g900 mb-3">계좌이체 (무통장 입금)</h2>
<div class="bg-blue-soft rounded-2xl p-4 mb-3"><div class="flex justify-between py-1"><span class="text-g500">입금 은행</span><span class="font-bold text-g900">${PAY_ACCOUNT.bank}</span></div><div class="flex justify-between py-1"><span class="text-g500">계좌번호</span><span class="font-bold text-g900 num">${PAY_ACCOUNT.no}</span></div><div class="flex justify-between py-1"><span class="text-g500">예금주</span><span class="font-bold text-g900">${PAY_ACCOUNT.holder}</span></div></div>
<div class="flex gap-2"><button onclick="copyText('${PAY_ACCOUNT.bank} ${PAY_ACCOUNT.no} ${PAY_ACCOUNT.holder}')" class="${BTN_GHOST} flex-1">계좌 복사</button><button onclick="notifyPaid()" class="${BTN} flex-1" ${pay==="결제 완료"?"disabled":""}>${pay==="결제 완료"?"결제 완료됨":"입금 완료 알림"}</button></div></div>
<div class="${CARD} p-7"><h2 class="text-[16px] font-bold text-g900 mb-1">세금계산서</h2><p class="text-[14px] text-g500 leading-relaxed">세금계산서는 <b>크놀AD(에이치알컴퍼니)</b>가 발행합니다. <button onclick="go('mypage')" class="text-blue font-bold underline">마이페이지</button>에서 사업자등록증을 제출하시면 입금 확인 후 발행됩니다.</p></div>
</div></div>`;}
function notifyPaid(){const c=S.activeCamp;if(!c){toast("캠페인을 선택해주세요");return;}toast("입금 완료를 알렸습니다 · 크놀AD 확인 후 결제 완료로 처리됩니다");}
function ytId(u){if(!u)return null;const m=u.match(/(?:v=|youtu\.be\/|shorts\/|embed\/)([A-Za-z0-9_-]{6,})/);return m?m[1]:null;}
function viewReport(){const c=S.activeCamp;const wf=c?wfOf(c):{};const urls=wf.urls||{};const list=[["YouTube",urls.yt,"text-red-500"],["Instagram",urls.ig,"text-pink-500"],["TikTok",urls.tt,"text-g800"]].filter(x=>x[1]);
const head=pageHeader("REPORT","인사이트 리포트",c?esc(c.brand_name)+" 캠페인":"");
if(!list.length)return `<div class="p-8 md:p-10">${head}<div class="max-w-xl"><div class="${CARD} p-14 text-center"><div class="w-14 h-14 rounded-[20px] bg-g100 grid place-items-center mx-auto mb-5"><i data-lucide="bar-chart-3" class="w-7 h-7 text-g300"></i></div><p class="text-[18px] font-bold text-g900 mb-1.5">업로드 완료 후 리포트가 제공됩니다</p><p class="text-[16px] text-g500 mb-5">크놀AD가 영상을 업로드하면 영상 URL·썸네일·조회수 인사이트가 여기에 표시됩니다.</p><div class="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-amber-50"><i data-lucide="clock" class="w-3.5 h-3.5 text-amber-600"></i><span class="text-[15px] font-bold text-amber-700">업로드 대기중</span></div></div></div></div>`;
const cards=list.map(x=>{const vid=x[0]==="YouTube"?ytId(x[1]):null;const thumb=vid?`<img src="https://i.ytimg.com/vi/${vid}/hqdefault.jpg" referrerpolicy="no-referrer" class="w-full aspect-video object-cover rounded-2xl mb-3" onerror="this.style.display='none'">`:`<div class="w-full aspect-video bg-g100 rounded-2xl mb-3 grid place-items-center text-g400"><i data-lucide="play-circle" class="w-10 h-10"></i></div>`;
return `<div class="${CARD} p-5">${thumb}<div class="flex items-center justify-between mb-3"><span class="font-bold ${x[2]}">${x[0]}</span><button onclick="openLink('${esc(x[1])}')" class="text-blue text-[13px] font-bold">영상 열기 ↗</button></div><div class="grid grid-cols-3 gap-2">${[["조회수","—"],["좋아요","—"],["댓글","—"]].map(sx=>`<div class="bg-g50 rounded-xl p-3 text-center"><p class="text-[12px] text-g400">${sx[0]}</p><p class="text-[18px] font-bold text-g900 num">${sx[1]}</p></div>`).join("")}</div><p class="text-[12px] text-g500 mt-2">* 조회수·시청자 인사이트는 추후 API 뷰어 연동 시 자동 표기됩니다.</p></div>`;}).join("");
return `<div class="p-8 md:p-10">${head}<div class="grid md:grid-cols-2 gap-4 max-w-3xl">${cards}</div></div>`;}


function viewCalendar(){setTimeout(loadMyCamps,30);const nd=new Date();if(S.calY==null){S.calY=nd.getFullYear();S.calM=nd.getMonth();}const y=S.calY,m=S.calM;
const startDow=new Date(y,m,1).getDay();const days=new Date(y,m+1,0).getDate();const todayStr=`${nd.getFullYear()}-${String(nd.getMonth()+1).padStart(2,'0')}-${String(nd.getDate()).padStart(2,'0')}`;
const ev=[];(S.myCamps||[]).forEach(a=>{if(a.preferred_date)ev.push({date:a.preferred_date,title:(a.brand_name||'')+" 업로드",type:"auto",campId:a.id});});
const sch=(S.activeCamp&&S.activeCamp.schedule)||[];sch.forEach(e=>ev.push({date:e.date,title:e.title,type:"manual",id:e.id}));
let cells="";for(let i=0;i<startDow;i++)cells+='<div></div>';
for(let d=1;d<=days;d++){const ds=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;const isT=ds===todayStr;const es=ev.filter(e=>e.date===ds);
cells+=`<div onclick="calAdd('${ds}')" class="min-h-[94px] border ${isT?'border-blue bg-blue-soft':'border-g100'} rounded-2xl p-2 cursor-pointer hover:bg-g50 transition-colors"><div class="text-[13px] font-bold ${isT?'text-blue':'text-g500'} mb-1">${d}</div>${es.map(e=>`<div onclick="event.stopPropagation();${e.type==='manual'?`calEdit('${e.id}')`:`calEditAuto('${e.campId}')`}" class="mb-1 text-[11px] px-1.5 py-1 rounded-lg ${e.type==='auto'?'bg-blue-tint text-blue':'bg-emerald-50 text-emerald-700'} truncate font-bold">${esc(e.title)}</div>`).join("")}</div>`;}
return `<div class="p-8 md:p-10">${pageHeader("SCHEDULE","캠페인 일정","신청한 업로드 희망일이 자동 표시됩니다 · 날짜를 클릭해 일정을 추가/수정/삭제하세요")}
<div class="${CARD} p-6 max-w-4xl"><div class="flex items-center justify-between mb-5"><button onclick="calPrev()" class="w-10 h-10 rounded-full bg-g100 grid place-items-center text-g600 hover:bg-g200 text-[18px] font-bold">‹</button><h2 class="text-[22px] font-bold text-g900">${y}년 ${m+1}월</h2><button onclick="calNext()" class="w-10 h-10 rounded-full bg-g100 grid place-items-center text-g600 hover:bg-g200 text-[18px] font-bold">›</button></div>
<div class="grid grid-cols-7 gap-1.5 mb-2 text-center text-[13px] font-bold text-g400">${["일","월","화","수","목","금","토"].map(d=>`<div>${d}</div>`).join("")}</div>
<div class="grid grid-cols-7 gap-1.5">${cells}</div>
<div class="flex gap-4 mt-5 text-[13px] text-g500 flex-wrap"><span class="inline-flex items-center gap-1.5"><span class="w-3 h-3 rounded bg-blue-tint"></span>업로드 예정 (신청값 자동)</span><span class="inline-flex items-center gap-1.5"><span class="w-3 h-3 rounded bg-emerald-50 border border-emerald-200"></span>직접 추가한 일정</span></div></div></div>`;}
function calPrev(){if(S.calM==null){const d=new Date();S.calY=d.getFullYear();S.calM=d.getMonth();}S.calM--;if(S.calM<0){S.calM=11;S.calY--;}render();}
function calNext(){if(S.calM==null){const d=new Date();S.calY=d.getFullYear();S.calM=d.getMonth();}S.calM++;if(S.calM>11){S.calM=0;S.calY++;}render();}
function calForm(title,dateVal,titleVal,delId,saveArg){return `<div class="flex items-center justify-between mb-3"><h3 class="text-[18px] font-bold text-g900">${title}</h3><button onclick="closeModal()" class="w-8 h-8 rounded-full bg-g100 grid place-items-center text-g500">✕</button></div><label class="block text-[14px] font-bold text-g600 mb-1">날짜</label><input id="calDate" type="date" value="${dateVal}" class="${INPUT} mb-3"><label class="block text-[14px] font-bold text-g600 mb-1">일정 제목</label><input id="calTitle" value="${titleVal}" placeholder="예: 쇼잉 업로드, 콘티 마감" class="${INPUT} mb-4"><div class="flex gap-2">${delId?`<button onclick="calDelete('${delId}')" class="${BTN_GHOST} text-red-600 px-5">삭제</button>`:''}<button onclick="calSave(${saveArg})" class="${BTN} flex-1">저장</button></div>`;}
function calAdd(ds){if(!S.activeCamp){toast("승인된 캠페인을 먼저 선택하세요");return;}modal(calForm("일정 추가",ds,"",null,"null"));}
function calEdit(id){const c=S.activeCamp;const e=((c&&c.schedule)||[]).find(x=>x.id===id);if(!e)return;modal(calForm("일정 수정",e.date,esc(e.title),id,`'${id}'`));}
function calSave(id){const c=S.activeCamp;if(!c){toast("캠페인을 선택하세요");return;}const date=gv("calDate"),title=(gv("calTitle")||"").trim();if(!date||!title){toast("날짜와 제목을 입력하세요");return;}let sch=((c.schedule)||[]).slice();if(id){sch=sch.map(x=>x.id===id?{id:id,date:date,title:title}:x);}else{sch.push({id:"e"+Date.now(),date:date,title:title});}calPersist(c,sch,"일정이 저장되었습니다");}
function calDelete(id){const c=S.activeCamp;if(!c)return;calPersist(c,((c.schedule)||[]).filter(x=>x.id!==id),"일정이 삭제되었습니다");}
function calPersist(c,sch,msg){c.schedule=sch;fetch(SUPA_URL+"/rest/v1/knollad_applications?id=eq."+c.id,{method:"PATCH",headers:Object.assign({"Content-Type":"application/json","Prefer":"return=minimal"},SH),body:JSON.stringify({schedule:sch})}).then(r=>{if(!r.ok)toast("저장 실패");}).catch(()=>toast("저장 오류"));closeModal();toast(msg);render();}
function calEditAuto(campId){const a=(S.myCamps||[]).find(x=>String(x.id)===String(campId));if(!a)return;modal(`<div class="flex items-center justify-between mb-3"><h3 class="text-[18px] font-bold text-g900 break-all">${esc(a.brand_name)} 업로드 희망일</h3><button onclick="closeModal()" class="w-8 h-8 rounded-full bg-g100 grid place-items-center text-g500">✕</button></div><p class="text-[13px] text-g500 mb-3">신청 시 입력한 업로드 희망일입니다. 변경하면 캠페인 정보에 반영됩니다.</p><input id="calDate" type="date" value="${esc(a.preferred_date||'')}" class="${INPUT} mb-4"><button onclick="calSaveAuto('${campId}')" class="${BTN} w-full">업로드 희망일 변경</button>`);}
function calSaveAuto(campId){const d=gv("calDate");const a=(S.myCamps||[]).find(x=>String(x.id)===String(campId));if(!a){return;}fetch(SUPA_URL+"/rest/v1/knollad_applications?id=eq."+campId,{method:"PATCH",headers:Object.assign({"Content-Type":"application/json","Prefer":"return=minimal"},SH),body:JSON.stringify({preferred_date:d})}).then(r=>{if(r.ok){a.preferred_date=d;toast("업로드 희망일이 변경되었습니다");}else toast("변경 실패");closeModal();render();}).catch(()=>toast("오류"));}
/* ===== ADMIN ===== */
function genPw(){return "kn"+Math.random().toString(36).slice(2,7)+Math.floor(Math.random()*90+10);}
function loadApps(){fetch(SUPA_URL+"/rest/v1/knollad_applications?select=*&order=created_at.desc",{headers:SH}).then(r=>r.json()).then(rows=>{ADM_ROWS=Array.isArray(rows)?rows:[];if(S.view==="admin-dashboard")renderAdmRows();else if(S.view==="admin-members")renderMembers();}).catch(()=>{const b=document.getElementById("admRows");if(b)b.innerHTML='<tr><td colspan="8" class="px-4 py-10 text-center text-g400">불러오기 실패</td></tr>';});}
function viewAdminList(){setTimeout(loadApps,30);return `<div class="p-8 md:p-10">${pageHeader("ADMIN","캠페인 관리","폼으로 접수된 실제 신청 데이터 · 승인 시 계정 자동 발급")}
<div class="grid grid-cols-2 md:grid-cols-4 gap-3 mb-6" id="admStats"></div>
<div class="${CARD} overflow-hidden"><div class="overflow-x-auto"><table class="w-full text-left min-w-[960px]"><thead><tr class="border-b border-g100 bg-g50">${["접수일","브랜드","담당자","이메일","연락처","채널 / 금액","상태","처리"].map(h=>`<th class="px-4 py-3 text-[13px] font-bold text-g500 whitespace-nowrap">${h}</th>`).join("")}</tr></thead><tbody id="admRows"><tr><td colspan="8" class="px-4 py-10 text-center text-g400">불러오는 중…</td></tr></tbody></table></div></div></div>`;}
function renderAdmRows(){const b=document.getElementById("admRows");if(!b)return;const rows=ADM_ROWS;
b.innerHTML=rows.length?rows.map(a=>{const chans=(a.channels||[]).map(c=>c.name).join(", ")||"-";const approved=a.status==="승인 완료";return `<tr class="border-b border-g100 last:border-0 hover:bg-g50 align-top"><td class="px-4 py-3 text-[13px] text-g400 num">${(a.created_at||"").slice(0,10)}</td><td class="px-4 py-3 font-bold text-g900 text-[15px]">${esc(a.brand_name)}</td><td class="px-4 py-3 text-g700 text-[15px]">${esc(a.contact_name)}</td><td class="px-4 py-3 text-g500 text-[14px]">${esc(a.email)}</td><td class="px-4 py-3 text-g500 text-[14px] num">${esc(a.phone)}</td><td class="px-4 py-3 text-[14px] max-w-[220px]"><div class="text-g700 truncate">${esc(chans)}</div><div class="text-blue font-bold num">${wonM(a.total_amount||0)}</div></td><td class="px-4 py-3">${statusBadge(a.status)}${approved&&a.account_pw?`<button onclick="showCreds('${esc(a.account_id||a.email)}','${esc(a.account_pw)}')" class="block mt-1 text-[12px] text-blue font-bold">계정/안내문</button>`:''}</td><td class="px-4 py-3"><div class="flex gap-1">${approved?'':`<button onclick="admApprove('${a.id}','${esc(a.email)}')" class="px-2.5 py-1.5 rounded-xl bg-blue text-white text-[12px] font-bold">승인</button>`}${approved?`<button onclick="admWorkflow('${a.id}')" class="px-2.5 py-1.5 rounded-xl bg-emerald-50 text-emerald-700 text-[12px] font-bold">워크플로우</button>`:''}<button onclick="admUpdate('${a.id}','진행중')" class="px-2.5 py-1.5 rounded-xl bg-g100 text-g700 text-[12px] font-bold">진행</button><button onclick="admUpdate('${a.id}','반려')" class="px-2.5 py-1.5 rounded-xl bg-red-50 text-red-600 text-[12px] font-bold">반려</button></div></td></tr>`;}).join(""):'<tr><td colspan="8" class="px-4 py-10 text-center text-g400">아직 접수된 신청이 없습니다. 폼에서 신청하면 여기에 표시됩니다.</td></tr>';
const s=document.getElementById("admStats");if(s){const c=k=>rows.filter(a=>a.status===k).length;s.innerHTML=[["전체 신청",rows.length],["검토 대기",c("검토 대기중")],["승인 완료",c("승인 완료")],["진행중",c("진행중")]].map(x=>`<div class="${CARD} p-5"><p class="text-[14px] text-g400 mb-1.5">${x[0]}</p><p class="font-display text-[30px] font-bold text-g900 num">${x[1]}</p></div>`).join("");}}
function admApprove(id,email){const pw=genPw();fetch(SUPA_URL+"/rest/v1/knollad_applications?id=eq."+id,{method:"PATCH",headers:Object.assign({"Content-Type":"application/json","Prefer":"return=minimal"},SH),body:JSON.stringify({status:"승인 완료",account_id:email,account_pw:pw,approved_at:new Date().toISOString(),wf:{step:2}})}).then(r=>{if(r.ok){loadApps();showCreds(email,pw);}else toast("승인 실패 (권한)");}).catch(()=>toast("승인 실패"));}
function admUpdate(id,status){fetch(SUPA_URL+"/rest/v1/knollad_applications?id=eq."+id,{method:"PATCH",headers:Object.assign({"Content-Type":"application/json","Prefer":"return=minimal"},SH),body:JSON.stringify({status})}).then(r=>{if(r.ok){toast(status+" 처리됨");loadApps();}else toast("처리 실패");}).catch(()=>toast("처리 실패"));}
function admWorkflow(id){const a=ADM_ROWS.find(x=>String(x.id)===String(id));if(!a){toast("불러오기 실패");return;}const wf=a.wf||{step:2};const step=wf.step;const stages=["문의","자료 공유","콘티 작성","콘티 컨펌","영상 제작","영상 컨펌","완료(리포트)"];const cur=stages[Math.min(step-1,6)];const u=wf.urls||{};
let action="";
if(step<=2)action=`<div class="bg-g50 rounded-2xl p-4 text-[15px] text-g600">고객의 <b>자료 제출</b>을 기다리는 단계입니다.</div>`;
else if(step===3)action=`<p class="text-[14px] font-bold text-g700 mb-2">콘티 전달 (고객에게)</p>${wf.note?`<div class="bg-orange-50 rounded-2xl p-3 mb-2 text-[13px] text-orange-700">수정요청: ${esc(wf.note)}</div>`:""}<input id="admConti" placeholder="콘티 링크 (드라이브/노션 등)" class="${INPUT} mb-2"><button onclick="admDeliverConti('${a.id}')" class="${BTN} w-full">콘티 전달하기 →</button>`;
else if(step===4)action=`<div class="bg-blue-soft rounded-2xl p-4 text-[15px] text-g700">콘티 전달 완료 · 고객 컨펌 대기 중</div>`;
else if(step===5)action=`<p class="text-[14px] font-bold text-g700 mb-2">영상 전달 (고객에게)</p>${wf.note?`<div class="bg-orange-50 rounded-2xl p-3 mb-2 text-[13px] text-orange-700">수정요청: ${esc(wf.note)}</div>`:""}<input id="admVideo" placeholder="영상 링크" class="${INPUT} mb-2"><button onclick="admDeliverVideo('${a.id}')" class="${BTN} w-full">영상 전달하기 →</button>`;
else if(step===6)action=`<div class="bg-blue-soft rounded-2xl p-4 text-[15px] text-g700">영상 전달 완료 · 고객 컨펌 대기 중</div>`;
else action=`<p class="text-[14px] font-bold text-g700 mb-2">업로드 URL 입력 (리포트 표기)</p><input id="admYt" placeholder="YouTube URL" value="${esc(u.yt||'')}" class="${INPUT} mb-2"><input id="admIg" placeholder="Instagram URL" value="${esc(u.ig||'')}" class="${INPUT} mb-2"><input id="admTt" placeholder="TikTok URL" value="${esc(u.tt||'')}" class="${INPUT} mb-2"><button onclick="admSaveUrls('${a.id}')" class="${BTN} w-full">업로드 URL 저장</button>`;
modal(`<div class="flex items-center justify-between mb-1"><h3 class="text-[19px] font-bold text-g900 break-all">${esc(a.brand_name)} 워크플로우</h3><button onclick="closeModal()" class="w-8 h-8 rounded-full bg-g100 grid place-items-center text-g500 flex-shrink-0">✕</button></div><p class="text-[14px] text-g500 mb-3">현재 단계: <b class="text-blue">${cur}</b> · 결제: <b>${esc(a.pay_status||"미결제")}</b></p><div class="space-y-2">${action}<button onclick="admConfirmPay('${a.id}')" class="${BTN_GHOST} w-full">입금 확인 → 결제 완료 처리</button></div><button onclick="closeModal()" class="${BTN_GHOST} w-full mt-3">닫기</button>`);}
function admWfSave(id,patch,msg){const a=ADM_ROWS.find(x=>String(x.id)===String(id));const wf=Object.assign({},(a&&a.wf)||{step:2},patch);fetch(SUPA_URL+"/rest/v1/knollad_applications?id=eq."+id,{method:"PATCH",headers:Object.assign({"Content-Type":"application/json","Prefer":"return=minimal"},SH),body:JSON.stringify({wf})}).then(r=>{if(r.ok){if(a)a.wf=wf;toast(msg||"저장되었습니다");closeModal();loadApps();}else toast("저장 실패");}).catch(()=>toast("저장 오류"));}
function admDeliverConti(id){const u=(gv("admConti")||"").trim();if(!u){toast("콘티 링크를 입력하세요");return;}admWfSave(id,{conti:u,step:4,note:null},"콘티가 전달되었습니다");}
function admDeliverVideo(id){const u=(gv("admVideo")||"").trim();if(!u){toast("영상 링크를 입력하세요");return;}admWfSave(id,{video:u,step:6,note:null},"영상이 전달되었습니다");}
function admSaveUrls(id){const urls={yt:(gv("admYt")||"").trim(),ig:(gv("admIg")||"").trim(),tt:(gv("admTt")||"").trim()};admWfSave(id,{urls,step:7},"업로드 URL이 저장되었습니다");}
function admConfirmPay(id){fetch(SUPA_URL+"/rest/v1/knollad_applications?id=eq."+id,{method:"PATCH",headers:Object.assign({"Content-Type":"application/json","Prefer":"return=minimal"},SH),body:JSON.stringify({pay_status:"결제 완료"})}).then(r=>{if(r.ok){toast("결제 완료 처리됨");closeModal();loadApps();}else toast("처리 실패");}).catch(()=>toast("오류"));}
function showCreds(email,pw){CRED_MSG="[크놀AD] 캠페인 신청이 승인되었습니다.\n\n■ 로그인 정보\n- 아이디(이메일): "+email+"\n- 비밀번호: "+pw+"\n- 로그인: https://cnolad.vercel.app  (로그인)\n\n승인된 계정으로 로그인하시면 채널 선택, 단가 확인, 자료 업로드, 컨펌, 업로드 일정, 리포트까지 실시간으로 확인하실 수 있습니다.\n감사합니다. 에이치알컴퍼니(주) 드림";
modal(`<div class="text-center"><div class="w-14 h-14 rounded-full bg-blue-tint grid place-items-center mx-auto mb-4"><i data-lucide="key-round" class="w-7 h-7 text-blue"></i></div><h3 class="text-[20px] font-bold text-g900 mb-1">계정 발급 완료</h3><p class="text-g500 text-[14px] mb-4">아래 안내문을 복사해 고객에게 전달하세요.</p></div>
<div class="bg-g50 rounded-[20px] p-4 space-y-2 text-[15px] mb-3"><div class="flex justify-between gap-3"><span class="text-g500">아이디</span><span class="font-bold text-g900 break-all text-right">${esc(email)}</span></div><div class="flex justify-between gap-3"><span class="text-g500">비밀번호</span><span class="font-bold text-blue num">${esc(pw)}</span></div></div>
<div class="bg-blue-soft rounded-[20px] p-4 text-[13px] text-g700 whitespace-pre-line max-h-40 overflow-y-auto mb-3">${esc(CRED_MSG)}</div>
<div class="flex gap-2"><button onclick="copyText(CRED_MSG)" class="${BTN} flex-1"><i data-lucide="copy" class="w-4 h-4"></i>승인 안내문 복사</button><button onclick="closeModal()" class="${BTN_GHOST} px-5">닫기</button></div>`);}
function memberCampaigns(email){const rows=ADM_ROWS.filter(a=>a.email===email);const items=rows.map(a=>`<div class="bg-g50 rounded-2xl p-3"><div class="flex items-center justify-between gap-3"><div class="min-w-0"><p class="font-bold text-g900">${esc(a.brand_name)}</p><p class="text-[12px] text-g500 truncate">${(a.created_at||"").slice(0,10)} · ${(a.channels||[]).map(c=>c.name).join(", ")||"-"} · ${wonM(a.total_amount||0)}</p></div>${statusBadge(a.status)}</div>${a.status==="승인 완료"?`<button onclick="closeModal();admWorkflow('${a.id}')" class="${BTN} w-full mt-2.5 py-2.5 text-[13px]"><i data-lucide="git-branch" class="w-4 h-4"></i>워크플로우 · 콘티/영상 전달</button>`:""}</div>`).join("");modal(`<div class="flex items-center justify-between mb-1"><h3 class="text-[19px] font-bold text-g900 break-all">${esc(email)}</h3><button onclick="closeModal()" class="w-8 h-8 rounded-full bg-g100 grid place-items-center text-g500 flex-shrink-0">✕</button></div><p class="text-[14px] text-g500 mb-4">신청 ${rows.length}건</p><div class="space-y-2 max-h-[55vh] overflow-y-auto">${items||'<p class="text-g400 text-center py-6">신청 내역이 없습니다.</p>'}</div><button onclick="closeModal()" class="${BTN} w-full mt-4">닫기</button>`);}
function addChannelByHandle(){const el=document.getElementById("newHandle");let h=((el?el.value:"")||"").trim().replace(/^@/,"");if(!h){toast("핸들을 입력해주세요");return;}toast("채널 정보를 불러오는 중…");fetch("https://www.googleapis.com/youtube/v3/channels?part=snippet,statistics&forHandle="+encodeURIComponent(h)+"&fields=items(id,snippet/title,snippet/thumbnails/medium/url,statistics/subscriberCount,statistics/viewCount,statistics/videoCount)&key="+YT_API_KEY).then(r=>r.json()).then(res=>{const it=(res.items||[])[0];if(!it){toast("채널을 찾을 수 없습니다");return;}if(CH.find(c=>c.id===it.id)){toast("이미 등록된 채널입니다");return;}const st=it.statistics||{},sn=it.snippet||{};CH.push({id:it.id,name:sn.title||h,read:null,region:"KR",plat:["YouTube"],handle:h,yt:+st.subscriberCount||0,views:+st.viewCount||0,vids:+st.videoCount||0,ig:null,tt:null,prod:65,pub:30,logo:(sn.thumbnails&&sn.thumbnails.medium)?sn.thumbnails.medium.url:null});toast("추가됨: "+(sn.title||h));render();}).catch(()=>toast("불러오기 실패"));}
function viewAdminChannels(){return `<div class="p-8 md:p-10">${pageHeader("CHANNEL DB","채널 관리",`총 ${CH.length}개 채널 · 핸들로 채널을 추가할 수 있습니다`)}<div class="${CARD} p-5 mb-4 flex items-center gap-3 flex-wrap"><div class="flex-1 min-w-[220px]"><input id="newHandle" placeholder="유튜브 핸들 입력 (예: mimtube777)" class="${INPUT}" onkeydown="if(event.key==='Enter')addChannelByHandle()"></div><button onclick="addChannelByHandle()" class="${BTN} px-6"><i data-lucide="plus" class="w-4 h-4"></i>채널 추가</button></div><div class="${CARD} overflow-hidden"><div class="overflow-x-auto"><table class="w-full text-[14px] min-w-[820px]"><thead><tr class="border-b border-g100 bg-g50">${["채널","플랫폼","구독자(YT)","총 조회수","평균","제작+발행","단순발행","공개"].map(h=>`<th class="px-5 py-3.5 text-left text-[13px] font-bold text-g500 whitespace-nowrap">${h}</th>`).join("")}</tr></thead><tbody>${CH.map(c=>`<tr class="border-b border-g100 last:border-0 hover:bg-g50"><td class="px-5 py-3"><div class="flex items-center gap-3">${logoEl(c,"w-8 h-8 text-sm")}<div><p class="font-bold text-g900">${esc(c.name)}</p><p class="text-[13px] text-g400">${REGION_LABEL[c.region]}${c.read?" · "+esc(c.read):""}</p></div></div></td><td class="px-5 py-3"><div class="flex gap-1 flex-wrap">${c.plat.map(platBadge).join("")}</div></td><td class="px-5 py-3 text-g600 num">${fmtSub(c.yt)}</td><td class="px-5 py-3 text-g600 num">${fmtView(c.views)}</td><td class="px-5 py-3 text-g600 num">${fmtView(avgView(c))}</td><td class="px-5 py-3 font-bold text-g900 num">${c.prod}만</td><td class="px-5 py-3 font-bold text-g900 num">${c.pub}만</td><td class="px-5 py-3"><button onclick="this.querySelector('span').classList.toggle('translate-x-[18px]');this.classList.toggle('bg-blue');this.classList.toggle('bg-g300')" class="relative inline-flex h-5 w-9 items-center rounded-full bg-blue transition-colors"><span class="inline-block w-3.5 h-3.5 rounded-full bg-white shadow-sm transform transition-transform translate-x-[18px]"></span></button></td></tr>`).join("")}</tbody></table></div></div></div>`;}
function viewAdminMembers(){setTimeout(loadApps,30);return `<div class="p-8 md:p-10">${pageHeader("MEMBER DB","회원DB","회사/브랜드별 신청 고객 · 행을 클릭하면 캠페인 내역을 볼 수 있습니다")}<div class="flex justify-end mb-4"><button onclick="exportMembersCSV()" class="${BTN} px-5 py-2.5 text-[14px]"><i data-lucide="download" class="w-4 h-4"></i>엑셀 다운로드</button></div>
<div class="${CARD} overflow-hidden"><div class="overflow-x-auto"><table class="w-full text-left min-w-[860px]"><thead><tr class="border-b border-g100 bg-g50">${["담당자","아이디(이메일)","회사/브랜드","연락처","신청 건수","상태","계정"].map(h=>`<th class="px-4 py-3 text-[13px] font-bold text-g500 whitespace-nowrap">${h}</th>`).join("")}</tr></thead><tbody id="memRows"><tr><td colspan="7" class="px-4 py-10 text-center text-g400">불러오는 중…</td></tr></tbody></table></div></div></div>`;}
function exportMembersCSV(){const map={};ADM_ROWS.forEach(a=>{const k=a.email;if(!map[k])map[k]={name:a.contact_name,email:a.email,phone:a.phone,brand:a.brand_name,count:0,last:a.status,pw:a.account_pw};map[k].count++;map[k].brand=a.brand_name;if(a.account_pw)map[k].pw=a.account_pw;if(a.status==="승인 완료")map[k].last="승인 완료";});const list=Object.values(map);if(!list.length){toast("내보낼 회원이 없습니다");return;}const q=v=>'"'+String(v==null?"":v).replace(/"/g,'""')+'"';const head=["담당자","아이디(이메일)","회사/브랜드","연락처","신청건수","상태","비밀번호"];const rows=list.map(m=>[m.name,m.email,m.brand,m.phone,m.count,m.last,m.pw||""].map(q).join(","));const csv="﻿"+head.map(q).join(",")+"\n"+rows.join("\n");const blob=new Blob([csv],{type:"text/csv;charset=utf-8;"});const url=URL.createObjectURL(blob);const el=document.createElement("a");el.href=url;el.download="크놀AD_회원DB_"+new Date().toISOString().slice(0,10)+".csv";document.body.appendChild(el);el.click();document.body.removeChild(el);URL.revokeObjectURL(url);toast("엑셀(CSV) 다운로드 완료");}
function renderMembers(){const b=document.getElementById("memRows");if(!b)return;const map={};ADM_ROWS.forEach(a=>{const k=a.email;if(!map[k])map[k]={name:a.contact_name,email:a.email,phone:a.phone,brand:a.brand_name,count:0,last:a.status,pw:a.account_pw};map[k].count++;map[k].brand=a.brand_name;if(a.account_pw)map[k].pw=a.account_pw;if(a.status==="승인 완료")map[k].last="승인 완료";});const list=Object.values(map);
b.innerHTML=list.length?list.map(m=>`<tr class="border-b border-g100 last:border-0 hover:bg-g50 cursor-pointer" onclick="memberCampaigns('${esc(m.email)}')"><td class="px-4 py-3 font-bold text-g900 text-[15px]">${esc(m.name)}</td><td class="px-4 py-3 text-g600 text-[14px]">${esc(m.email)}</td><td class="px-4 py-3 text-g700 text-[14px] font-bold">${esc(m.brand)}</td><td class="px-4 py-3 text-g600 num text-[14px]">${esc(m.phone)}</td><td class="px-4 py-3 num text-[14px]">${m.count}건</td><td class="px-4 py-3">${statusBadge(m.last)}</td><td class="px-4 py-3">${m.pw?`<button onclick="event.stopPropagation();showCreds('${esc(m.email)}','${esc(m.pw)}')" class="text-[13px] text-blue font-bold">안내문 복사</button>`:'<span class="text-g300 text-[13px]">미발급</span>'}</td></tr>`).join(""):'<tr><td colspan="7" class="px-4 py-10 text-center text-g400">회원이 없습니다.</td></tr>';}

/* ===== LIVE ===== */
let _liveDone=false,_liveTried=false;
function maybeLiveRefresh(){
  if(_liveDone||_liveTried)return;_liveTried=true;
  const ids=CH.map(c=>c.id);
  fetch(`https://www.googleapis.com/youtube/v3/channels?part=snippet,statistics&id=${ids.join(",")}&fields=items(id,snippet/thumbnails/medium/url,statistics/subscriberCount,statistics/viewCount,statistics/videoCount)&key=${YT_API_KEY}`)
  .then(r=>r.json()).then(res=>{(res.items||[]).forEach(it=>{const c=CH.find(x=>x.id===it.id);if(!c)return;if(it.snippet&&it.snippet.thumbnails&&it.snippet.thumbnails.medium)c.logo=it.snippet.thumbnails.medium.url;if(it.statistics){c.yt=+it.statistics.subscriberCount;c.views=+it.statistics.viewCount;c.vids=+it.statistics.videoCount;}});
    _liveDone=true;
    if(S.view==="channel-picker"||S.view==="cust-channels")updateTable();
    else if(document.getElementById("selBox")){document.getElementById("selBox").innerHTML=SEL.size?selectedSummary():'';if(window.lucide)lucide.createIcons();}
  }).catch(()=>{_liveTried=false;});
}
function toast(msg){let t=document.getElementById("toast");if(!t){t=document.createElement("div");t.id="toast";t.className="fixed bottom-8 left-1/2 z-[400] px-5 py-3 rounded-[20px] bg-g900 text-white text-[15px] font-bold shadow-pop transition-all";t.style.opacity=0;document.body.appendChild(t);}t.textContent=msg;t.style.transform="translateX(-50%) translateY(0)";t.style.opacity=1;clearTimeout(t._t);t._t=setTimeout(()=>t.style.opacity=0,2800);}
render();
