function admWfMsg(id){const a=ADM_ROWS.find(x=>String(x.id)===String(id));if(!a)return;const t=(gv("admMsgInput")||"").trim();if(!t){toast("메시지를 입력하세요");return;}const notes=(a.notes||[]).slice();notes.push({who:"크놀AD",role:"knoll",text:t,at:new Date().toISOString()});a.notes=notes;fetch(SUPA_URL+"/rest/v1/knollad_applications?id=eq."+id,{method:"PATCH",headers:Object.assign({"Content-Type":"application/json","Prefer":"return=minimal"},SH),body:JSON.stringify({notes:notes})}).then(r=>{if(r.ok){toast("메시지를 보냈습니다");loadApps();}else toast("저장 실패");}).catch(()=>toast("오류"));}
function viewWorkflow(){const c=S.activeCamp;if(!c){setTimeout(loadMyCamps,30);return `<div class="p-8 md:p-10">${pageHeader("ORDER","캠페인 진행")}<div class="${CARD} p-12 text-center text-g500 text-[16px]">승인된 캠페인이 있어야 진행할 수 있습니다.<br>‘캠페인 관리’에서 캠페인을 선택하세요.</div></div>`;}
const wf=wfOf(c);const cur=wf.step;const pct=Math.round(Math.min(cur,7)/7*100);markSeen(c,"cust");
let action="";
if(cur>=7){const paid=c.pay_status==="결제 완료";action=`<div class="text-center py-2"><div class="w-14 h-14 rounded-full bg-emerald-50 grid place-items-center mx-auto mb-3"><i data-lucide="party-popper" class="w-7 h-7 text-emerald-500"></i></div><p class="text-[17px] font-bold text-g900 mb-1">제작·업로드가 완료되었습니다</p><p class="text-[14px] text-g500 mb-4">리포트에서 성과를 확인하고 결제를 진행해주세요.</p><div class="flex gap-2"><button onclick="go('report')" class="${BTN_GHOST} flex-1">리포트 보기</button><button onclick="go('settlement')" class="${BTN} flex-1">${paid?"결제 완료됨":"결제 / 정산"}</button></div></div>`;}
else action=wfPanel(WF[cur-1]);
const notes=c.notes||[];
return `<div class="p-8 md:p-10">${pageHeader("ORDER","캠페인 진행",esc(c.brand_name)+" · 진행 상황과 주고받는 자료를 한눈에 확인하세요")}
<div class="${CARD} p-6 mb-5">${wfStepper(cur)}<div class="flex items-center gap-3 mt-5"><div class="flex-1 bg-g100 rounded-full h-2 overflow-hidden"><div class="h-2 rounded-full transition-all duration-500" style="width:${pct}%;background:linear-gradient(90deg,#3182F6,#1B64DA)"></div></div><span class="text-[14px] font-bold text-blue num">${pct}%</span></div></div>
<div class="grid lg:grid-cols-5 gap-5"><div class="lg:col-span-3 space-y-5">
<div class="${CARD} p-6 border-2 border-blue"><div class="flex items-center gap-2 mb-3"><span class="w-2 h-2 rounded-full bg-blue"></span><h2 class="text-[18px] font-bold text-g900">현재 진행 상황</h2></div>${action}</div>
<div class="${CARD} p-6"><h2 class="text-[16px] font-bold text-g900 mb-4">진행 내역 · 주고받은 자료</h2>${wfActivityFeed(c)}</div></div>
<div class="lg:col-span-2"><div class="${CARD} p-6 lg:sticky lg:top-6"><h2 class="text-[16px] font-bold text-g900 mb-3">메시지</h2><div class="space-y-2 max-h-[48vh] overflow-y-auto mb-3 pr-1">${notes.length?notes.map(noteRow).join(""):'<p class="text-g400 text-center py-8 text-[14px]">메시지가 없습니다.<br>궁금한 점을 자유롭게 남겨보세요.</p>'}</div><textarea id="wfMsgInput" rows="2" placeholder="메시지 입력…" class="${INPUT} resize-none mb-2"></textarea><button onclick="wfMsg()" class="${BTN} w-full py-3">보내기</button></div></div></div></div>`;}
const PAY_ACCOUNT={bank:"우리은행",no:"1005-504-167163",holder:"에이치알컴퍼니(주)"};
function viewSettlement(){setTimeout(loadMyCamps,30);const camps=(S.myCamps||[]).filter(a=>a.status==="승인 완료");
const amt=camps.reduce((t,a)=>t+(a.total_amount||0),0);const won=amt*10000;const vat=won*0.1;const tot=won*1.1;
const allPaid=camps.length>0&&camps.every(a=>a.pay_status==="결제 완료");const anyChk=camps.some(a=>a.pay_status==="입금 확인중");
const pay=allPaid?"결제 완료":anyChk?"입금 확인중":"결제 대기중";
const head=pageHeader("PAYMENT","결제 / 정산","캠페인 대금은 에이치알컴퍼니(주) 계좌로 입금해주세요");
if(!camps.length)return `<div class="p-8 md:p-10"><div class="max-w-2xl">${head}<div class="${CARD} p-12 text-center text-g500 text-[16px]">승인 완료된 캠페인이 없습니다.</div></div></div>`;
return `<div class="p-8 md:p-10"><div class="max-w-2xl">${head}
<div class="${CARD} p-7 mb-4"><div class="flex items-center justify-between mb-4"><h2 class="text-[16px] font-bold text-g900">결제 금액 · 전체 ${camps.length}건 합산</h2>${statusBadge(pay)}</div>
<div class="space-y-2 pb-3 mb-1 border-b border-g100">${camps.map(a=>`<div class="flex justify-between items-center gap-2 text-[14px]"><span class="text-g700 truncate flex items-center gap-2 min-w-0"><span class="font-bold flex-shrink-0">${esc(a.brand_name)}</span><span class="text-g400 text-[12px] truncate">${(a.channels||[]).map(c=>c.name).join(", ")}</span></span><span class="flex items-center gap-2 flex-shrink-0"><span class="num text-g700">${((a.total_amount||0)*10000).toLocaleString()}원</span>${statusBadge(a.pay_status||"결제 대기중")}</span></div>`).join("")}</div>
<div class="flex justify-between py-2 border-b border-g100"><span class="text-g500">공급가액 합계 (${camps.length}건)</span><span class="font-bold num">${wonM(amt)}</span></div>
<div class="flex justify-between py-2 border-b border-g100"><span class="text-g500">부가세 (VAT 10%)</span><span class="num text-g600">${vat.toLocaleString()}원</span></div>
<div class="flex justify-between py-3"><span class="font-bold text-g900">총 결제금액 (합산)</span><span class="font-bold text-blue text-[18px] num">${tot.toLocaleString()}원</span></div></div>
<div class="${CARD} p-7 mb-4"><h2 class="text-[16px] font-bold text-g900 mb-3">계좌이체 (무통장 입금)</h2>
<div class="bg-blue-soft rounded-2xl p-4 mb-3"><div class="flex justify-between py-1"><span class="text-g500">입금 은행</span><span class="font-bold text-g900">${PAY_ACCOUNT.bank}</span></div><div class="flex justify-between py-1"><span class="text-g500">계좌번호</span><span class="font-bold text-g900 num">${PAY_ACCOUNT.no}</span></div><div class="flex justify-between py-1"><span class="text-g500">예금주</span><span class="font-bold text-g900">${PAY_ACCOUNT.holder}</span></div></div>
<div class="flex gap-2"><button onclick="copyText('${PAY_ACCOUNT.bank} ${PAY_ACCOUNT.no} ${PAY_ACCOUNT.holder}')" class="${BTN_GHOST} flex-1">계좌 복사</button><button onclick="notifyPaidAll()" class="${BTN} flex-1" ${allPaid?"disabled":""}>${allPaid?"결제 완료됨":anyChk?"입금 확인중":"입금 완료 알림"}</button></div></div>
<div class="${CARD} p-7"><h2 class="text-[16px] font-bold text-g900 mb-1">세금계산서</h2><p class="text-[14px] text-g500 leading-relaxed">세금계산서는 <b>크놀AD(에이치알컴퍼니)</b>가 발행합니다. <button onclick="go('mypage')" class="text-blue font-bold underline">마이페이지</button>에서 사업자등록증을 제출하시면 입금 확인 후 발행됩니다.</p></div>
</div></div>`;}
function notifyPaidAll(){const camps=(S.myCamps||[]).filter(a=>a.status==="승인 완료"&&a.pay_status!=="결제 완료");if(!camps.length){toast("결제할 캠페인이 없습니다");return;}let done=0;camps.forEach(a=>{fetch(SUPA_URL+"/rest/v1/knollad_applications?id=eq."+a.id,{method:"PATCH",headers:Object.assign({"Content-Type":"application/json","Prefer":"return=minimal"},SH),body:JSON.stringify({pay_status:"입금 확인중"})}).then(r=>{if(r.ok)a.pay_status="입금 확인중";done++;if(done===camps.length)render();}).catch(()=>{done++;if(done===camps.length)render();});});toast("입금 완료를 알렸습니다 · 크놀AD 확인 후 결제 완료 처리됩니다");}
function ytId(u){if(!u)return null;const m=u.match(/(?:v=|youtu\.be\/|shorts\/|embed\/)([A-Za-z0-9_-]{6,})/);return m?m[1]:null;}
function viewReport(){const c=S.activeCamp;const wf=c?wfOf(c):{};const urls=wf.urls||{};const list=[["YouTube",urls.yt,"text-red-500"],["Instagram",urls.ig,"text-pink-500"],["TikTok",urls.tt,"text-g800"]].filter(x=>x[1]);
const head=pageHeader("REPORT","인사이트 리포트",c?esc(c.brand_name)+" 캠페인":"");
if(!list.length)return `<div class="p-8 md:p-10">${head}<div class="max-w-xl"><div class="${CARD} p-14 text-center"><div class="w-14 h-14 rounded-[20px] bg-g100 grid place-items-center mx-auto mb-5"><i data-lucide="bar-chart-3" class="w-7 h-7 text-g300"></i></div><p class="text-[18px] font-bold text-g900 mb-1.5">업로드 완료 후 리포트가 제공됩니다</p><p class="text-[16px] text-g500 mb-5">크놀AD가 영상을 업로드하면 영상 URL·썸네일·조회수 인사이트가 여기에 표시됩니다.</p><div class="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-amber-50"><i data-lucide="clock" class="w-3.5 h-3.5 text-amber-600"></i><span class="text-[15px] font-bold text-amber-700">업로드 대기중</span></div></div></div></div>`;
const cards=list.map(x=>{const vid=x[0]==="YouTube"?ytId(x[1]):null;const thumb=vid?`<img src="https://i.ytimg.com/vi/${vid}/hqdefault.jpg" referrerpolicy="no-referrer" class="w-full aspect-video object-cover rounded-2xl mb-3" onerror="this.style.display='none'">`:`<div class="w-full aspect-video bg-g100 rounded-2xl mb-3 grid place-items-center text-g400"><i data-lucide="play-circle" class="w-10 h-10"></i></div>`;
return `<div class="${CARD} p-5">${thumb}<div class="flex items-center justify-between mb-3"><span class="font-bold ${x[2]}">${x[0]}</span><button onclick="openLink('${esc(x[1])}')" class="text-blue text-[13px] font-bold">영상 열기 ↗</button></div><p class="text-[12px] text-g400 truncate -mt-1 mb-3">${esc(x[1])}</p><div class="grid grid-cols-3 gap-2">${[["조회수","—"],["좋아요","—"],["댓글","—"]].map(sx=>`<div class="bg-g50 rounded-xl p-3 text-center"><p class="text-[12px] text-g400">${sx[0]}</p><p class="text-[18px] font-bold text-g900 num">${sx[1]}</p></div>`).join("")}</div><p class="text-[12px] text-g500 mt-2">* 조회수·시청자 인사이트는 추후 API 뷰어 연동 시 자동 표기됩니다.</p></div>`;}).join("");
return `<div class="p-8 md:p-10">${head}<div class="grid md:grid-cols-2 gap-4 max-w-3xl">${cards}</div></div>`;}


function viewCalendar(){setTimeout(loadMyCamps,30);const nd=new Date();if(S.calY==null){S.calY=nd.getFullYear();S.calM=nd.getMonth();}const y=S.calY,m=S.calM;
const startDow=new Date(y,m,1).getDay();const days=new Date(y,m+1,0).getDate();const todayStr=`${nd.getFullYear()}-${String(nd.getMonth()+1).padStart(2,'0')}-${String(nd.getDate()).padStart(2,'0')}`;
const ev=[];(S.myCamps||[]).forEach(a=>{if(a.preferred_date)ev.push({date:a.preferred_date,title:(a.brand_name||'')+" 업로드",type:"auto",campId:a.id});});
const sch=(S.activeCamp&&S.activeCamp.schedule)||[];sch.forEach(e=>ev.push({date:e.date,title:e.title,type:"manual",id:e.id}));
let cells="";for(let i=0;i<startDow;i++)cells+='<div></div>';
for(let d=1;d<=days;d++){const ds=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;const isT=ds===todayStr;const es=ev.filter(e=>e.date===ds);
cells+=`<div onclick="calAdd('${ds}')" class="min-h-[120px] md:min-h-[140px] border ${isT?'border-blue bg-blue-soft':'border-g100'} rounded-2xl p-2.5 cursor-pointer hover:bg-g50 transition-colors"><div class="text-[15px] font-bold ${isT?'text-blue':'text-g500'} mb-1">${d}</div>${es.map(e=>`<div onclick="event.stopPropagation();${e.type==='manual'?`calEdit('${e.id}')`:`calEditAuto('${e.campId}')`}" class="mb-1 text-[12px] px-2 py-1 rounded-lg ${e.type==='auto'?'bg-blue-tint text-blue':'bg-emerald-50 text-emerald-700'} truncate font-bold">${esc(e.title)}</div>`).join("")}</div>`;}
return `<div class="p-8 md:p-10">${pageHeader("SCHEDULE","캠페인 일정","신청한 업로드 희망일이 자동 표시됩니다 · 날짜를 클릭해 일정을 추가/수정/삭제하세요")}
<div class="${CARD} p-6 md:p-8"><div class="flex items-center justify-between mb-5"><button onclick="calPrev()" class="w-10 h-10 rounded-full bg-g100 grid place-items-center text-g600 hover:bg-g200 text-[18px] font-bold">‹</button><h2 class="text-[22px] font-bold text-g900">${y}년 ${m+1}월</h2><button onclick="calNext()" class="w-10 h-10 rounded-full bg-g100 grid place-items-center text-g600 hover:bg-g200 text-[18px] font-bold">›</button></div>
<div class="grid grid-cols-7 gap-2 mb-2 text-center text-[14px] font-bold text-g400">${["일","월","화","수","목","금","토"].map(d=>`<div>${d}</div>`).join("")}</div>
<div class="grid grid-cols-7 gap-2">${cells}</div>
<div class="flex gap-4 mt-5 text-[13px] text-g500 flex-wrap"><span class="inline-flex items-center gap-1.5"><span class="w-3 h-3 rounded bg-blue-tint"></span>업로드 예정 (신청값 자동)</span><span class="inline-flex items-center gap-1.5"><span class="w-3 h-3 rounded bg-emerald-50 border border-emerald-200"></span>직접 추가한 일정</span></div></div></div>`;}
function calPrev(){if(S.calM==null){const d=new Date();S.calY=d.getFullYear();S.calM=d.getMonth();}S.calM--;if(S.calM<0){S.calM=11;S.calY--;}render();}
function calNext(){if(S.calM==null){const d=new Date();S.calY=d.getFullYear();S.calM=d.getMonth();}S.calM++;if(S.calM>11){S.calM=0;S.calY++;}render();}
function calForm(title,dateVal,titleVal,delId,saveArg){return `<div class="flex items-center justify-between mb-3"><h3 class="text-[18px] font-bold text-g900">${title}</h3><button onclick="closeModal()" class="w-8 h-8 rounded-full bg-g100 grid place-items-center text-g500">✕</button></div><label class="block text-[14px] font-bold text-g600 mb-1">날짜</label><input id="calDate" type="date" value="${dateVal}" class="${INPUT} mb-3"><label class="block text-[14px] font-bold text-g600 mb-1">일정 제목</label><input id="calTitle" value="${titleVal}" placeholder="예: 쇼잉 업로드, 콘티 마감" class="${INPUT} mb-4"><div class="flex gap-2">${delId?`<button onclick="calDelete('${delId}')" class="${BTN_GHOST} text-red-600 px-5">삭제</button>`:''}<button onclick="calSave(${saveArg})" class="${BTN} flex-1">저장</button></div>`;}
function calAdd(ds){if(!S.activeCamp){toast("승인된 캠페인을 먼저 선택하세요");return;}modal(calForm("일정 추가",ds,"",null,"null"));}
function calEdit(id){const c=S.activeCamp;const e=((c&&c.schedule)||[]).find(x=>x.id===id);if(!e)return;modal(calForm("일정 수정",e.date,esc(e.title),id,`'${id}'`));}
function calSave(id){const c=S.activeCamp;if(!c){toast("캠페인을 선택하세요");return;}const date=gv("calDate"),title=(gv("calTitle")||"").trim();if(!date||!title){toast("날짜와 제목을 입력하세요");return;}let sch=((c.schedule)||[]).slice();if(id){sch=sch.map(x=>x.id===id?{id:id,date:date,title:title}:x);}else{sch.push({id:"e"+Date.now(),date:date,title:title});}calPersist(c,sch,"일정이 저장되었습니다");}
function calDelete(id){const c=S.activeCamp;if(!c)return;calPersist(c,((c.schedule)||[]).filter(x=>x.id!==id),"일정이 삭제되었습니다");}
function calPersist(c,sch,msg){c.schedule=sch;fetch(SUPA_URL+"/rest/v1/knollad_applications?id=eq."+c.id,{method:"PATCH",headers:Object.assign({"Content-Type":"application/json","Prefer":"return=minimal"},SH),body:JSON.stringify({schedule:sch})}).then(r=>{if(!r.ok)toast("저장 실패");}).catch(()=>toast("저장 오류"));closeModal();toast(msg);render();}
function calEditAuto(campId){const a=(S.myCamps||[]).find(x=>String(x.id)===String(campId));if(!a)return;modal(`<div class="flex items-center justify-between mb-3"><h3 class="text-[18px] font-bold text-g900 break-all">${esc(a.brand_name)} 업로드 희망일</h3><button onclick="closeModal()" class="w-8 h-8 rounded-full bg-g100 grid place-items-center text-g500">✕</button></div><p class="text-[13px] text-g500 mb-3">신청 시 입력한 업로드 희망일입니다. 변경하면 캠페인 정보에 반영됩니다.</p><input id="calDate" type="date" value="${esc(a.preferred_date||'')}" class="${INPUT} mb-4"><button onclick="calSaveAuto('${campId}')" class="${BTN} w-full">업로드 희망일 변경</button>`);}
function calSaveAuto(campId){const d=gv("calDate");const a=(S.myCamps||[]).find(x=>String(x.id)===String(campId));if(!a){return;}fetch(SUPA_URL+"/rest/v1/knollad_applications?id=eq."+campId,{method:"PATCH",headers:Object.assign({"Content-Type":"application/json","Prefer":"return=minimal"},SH),body:JSON.stringify({preferred_date:d})}).then(r=>{if(r.ok){a.preferred_date=d;toast("업로드 희망일이 변경되었습니다");}else toast("변경 실패");closeModal();render();}).catch(()=>toast("오류"));}
/* ===== ADMIN ===== */
function genPw(){return "kn"+Math.random().toString(36).slice(2,7)+Math.floor(Math.random()*90+10);}
function loadApps(){fetch(SUPA_URL+"/rest/v1/knollad_applications?select=*&order=created_at.desc",{headers:SH}).then(r=>r.json()).then(rows=>{ADM_ROWS=Array.isArray(rows)?rows:[];if(S.view==="admin-dashboard")renderAdmRows();else if(S.view==="admin-members")renderMembers();else if(S.view==="admin-workflow")render();else if(S.view==="admin-calendar")render();else if(S.view==="admin-todo")render();}).catch(()=>{const b=document.getElementById("admRows");if(b)b.innerHTML='<tr><td colspan="9" class="px-4 py-10 text-center text-g400">불러오기 실패</td></tr>';});}
function viewAdminList(){setTimeout(loadApps,30);return `<div class="p-8 md:p-10">${pageHeader("ADMIN","캠페인 관리","폼으로 접수된 실제 신청 데이터 · 승인 시 계정 자동 발급")}
<div class="grid grid-cols-2 md:grid-cols-4 gap-3 mb-6" id="admStats"></div>
<div class="${CARD} overflow-hidden"><div class="overflow-x-auto"><table class="w-full text-left min-w-[960px]"><thead><tr class="border-b border-g100 bg-g50">${["접수일","브랜드","담당자","이메일","연락처","채널 / 금액","상태","결제","처리"].map(h=>`<th class="px-4 py-3 text-[13px] font-bold text-g500 whitespace-nowrap">${h}</th>`).join("")}</tr></thead><tbody id="admRows"><tr><td colspan="9" class="px-4 py-10 text-center text-g400">불러오는 중…</td></tr></tbody></table></div></div></div>`;}
function renderAdmRows(){const b=document.getElementById("admRows");if(!b)return;const rows=ADM_ROWS;
b.innerHTML=rows.length?rows.map(a=>{const chans=(a.channels||[]).map(c=>c.name).join(", ")||"-";const approved=a.status==="승인 완료";const isMember=ADM_ROWS.some(x=>x.email===a.email&&x.account_pw&&x.status==="승인 완료"&&String(x.id)!==String(a.id));return `<tr class="border-b border-g100 last:border-0 hover:bg-g50 align-top"><td class="px-4 py-3 text-[13px] text-g400 num">${(a.created_at||"").slice(0,10)}</td><td class="px-4 py-3 font-bold text-g900 text-[15px]">${esc(a.brand_name)}</td><td class="px-4 py-3 text-g700 text-[15px]">${esc(a.contact_name)}</td><td class="px-4 py-3 text-g500 text-[14px]">${esc(a.email)}</td><td class="px-4 py-3 text-g500 text-[14px] num">${esc(a.phone)}</td><td class="px-4 py-3 text-[14px] max-w-[220px]"><div class="text-g700 truncate">${esc(chans)}</div><div class="text-blue font-bold num">${wonM(a.total_amount||0)}</div></td><td class="px-4 py-3">${statusBadge(a.status)}${approved&&a.account_pw?`<button onclick="showCreds('${esc(a.account_id||a.email)}','${esc(a.account_pw)}')" class="block mt-1 text-[12px] text-blue font-bold">계정/안내문</button>`:''}</td><td class="px-4 py-3">${statusBadge(a.pay_status||"결제 대기중")}${approved?`<div class="mt-1">${a.pay_status==="결제 완료"?`<button onclick="admSetPay('${a.id}','결제 대기중')" class="text-[11px] text-g500 font-bold">대기로</button>`:`<button onclick="admSetPay('${a.id}','결제 완료')" class="text-[11px] text-emerald-600 font-bold">결제완료 처리</button>`}</div>`:""}</td><td class="px-4 py-3"><div class="flex gap-1">${approved?'':`<button onclick="admApprove('${a.id}','${esc(a.email)}')" class="px-2.5 py-1.5 rounded-xl text-[12px] font-bold" style="background:#3182F6;color:#fff">${isMember?"승인·기존회원":"승인"}</button>`}${approved?`<button onclick="openAdmWf('${a.id}')" class="px-2.5 py-1.5 rounded-xl bg-emerald-50 text-emerald-700 text-[12px] font-bold">워크플로우</button>`:''}<button onclick="admUpdate('${a.id}','진행중')" class="px-2.5 py-1.5 rounded-xl bg-g100 text-g700 text-[12px] font-bold">진행</button><button onclick="admUpdate('${a.id}','반려')" class="px-2.5 py-1.5 rounded-xl bg-red-50 text-red-600 text-[12px] font-bold">반려</button><button onclick="admDelete('${a.id}','${esc(a.brand_name)}')" class="px-2.5 py-1.5 rounded-xl text-[12px] font-bold" style="background:#191F28;color:#fff">삭제</button></div></td></tr>`;}).join(""):'<tr><td colspan="9" class="px-4 py-10 text-center text-g400">아직 접수된 신청이 없습니다. 폼에서 신청하면 여기에 표시됩니다.</td></tr>';
const s=document.getElementById("admStats");if(s){const c=k=>rows.filter(a=>a.status===k).length;s.innerHTML=[["전체 신청",rows.length],["검토 대기",c("검토 대기중")],["승인 완료",c("승인 완료")],["진행중",c("진행중")]].map(x=>`<div class="${CARD} p-5"><p class="text-[14px] text-g400 mb-1.5">${x[0]}</p><p class="font-display text-[30px] font-bold text-g900 num">${x[1]}</p></div>`).join("");}}
function admApprove(id,email){const a=ADM_ROWS.find(x=>String(x.id)===String(id))||{};const now=new Date().toISOString();fetch(SUPA_URL+"/rest/v1/knollad_members?email=eq."+encodeURIComponent(email)+"&select=password&limit=1",{headers:SH}).then(r=>r.json()).then(rows=>{const ex=rows&&rows[0];const pw=ex?ex.password:genPw();const doPatch=function(){fetch(SUPA_URL+"/rest/v1/knollad_applications?id=eq."+id,{method:"PATCH",headers:Object.assign({"Content-Type":"application/json","Prefer":"return=minimal"},SH),body:JSON.stringify({status:"승인 완료",account_id:email,account_pw:pw,approved_at:now,wf:{step:2}})}).then(r=>{if(r.ok){loadApps();if(ex){toast("기존 회원 승인 완료 · 계정 유지");}else{showCreds(email,pw);}}else toast("승인 실패 (권한)");}).catch(()=>toast("승인 실패"));};if(ex){doPatch();}else{fetch(SUPA_URL+"/rest/v1/knollad_members",{method:"POST",headers:Object.assign({"Content-Type":"application/json","Prefer":"return=minimal"},SH),body:JSON.stringify({email:email,password:pw,contact_name:a.contact_name,brand_name:a.brand_name})}).then(function(){doPatch();}).catch(function(){doPatch();});}}).catch(()=>toast("승인 오류"));}
function admUpdate(id,status){fetch(SUPA_URL+"/rest/v1/knollad_applications?id=eq."+id,{method:"PATCH",headers:Object.assign({"Content-Type":"application/json","Prefer":"return=minimal"},SH),body:JSON.stringify({status})}).then(r=>{if(r.ok){toast(status+" 처리됨");loadApps();}else toast("처리 실패");}).catch(()=>toast("처리 실패"));}
function admDelete(id,brand){modal(`<div class="text-center"><div class="w-14 h-14 rounded-full bg-red-50 grid place-items-center mx-auto mb-4"><i data-lucide="trash-2" class="w-7 h-7 text-red-500"></i></div><h3 class="text-[19px] font-bold text-g900 mb-1">캠페인을 삭제할까요?</h3><p class="text-g600 text-[15px] font-bold mb-1">${esc(brand)}</p><p class="text-[13px] text-red-500 mb-5 leading-relaxed">삭제하면 <b>고객 캠페인 현황에서도 사라지며</b><br>되돌릴 수 없습니다. 정말 삭제하시겠습니까?</p></div><div class="flex gap-2"><button onclick="closeModal()" class="${BTN_GHOST} flex-1">취소</button><button onclick="admDeleteConfirm('${id}')" class="flex-1 inline-flex items-center justify-center gap-2 px-7 py-4 rounded-[20px] font-bold text-[17px] active:scale-[0.97]" style="background:#EF4444;color:#fff">최종 삭제</button></div>`);}
function admDeleteConfirm(id){fetch(SUPA_URL+"/rest/v1/knollad_applications?id=eq."+id,{method:"DELETE",headers:Object.assign({"Prefer":"return=minimal"},SH)}).then(r=>{if(r.ok){toast("캠페인이 삭제되었습니다");closeModal();loadApps();}else toast("삭제 실패 (권한)");}).catch(()=>toast("삭제 오류"));}
function sendStepMail(id){const a=ADM_ROWS.find(x=>String(x.id)===String(id));if(!a)return;if(!a.email){toast("고객 이메일이 없습니다");return;}const wf=a.wf||{step:2};const stages=["문의 접수","자료 공유","콘티 작성","콘티 컨펌","영상 제작","영상 컨펌","완료 · 리포트"];const lbl=stages[Math.min(wf.step-1,6)];const bn=a.brand_name||"캠페인";const subj="[크놀AD] "+bn+" 진행 알림 · "+lbl;const html="<div style=\"font-family:sans-serif;font-size:15px;color:#191F28\">안녕하세요, <b>"+esc(bn)+"</b> 캠페인 담당자님.<br><br>현재 진행 단계: <b>"+esc(lbl)+"</b><br>크놀AD에서 진행 상황을 확인해 주세요.<br><br><a href=\"https://cnolad.vercel.app\">https://cnolad.vercel.app</a></div>";toast("알림 메일 발송 중…");fetch(SUPA_URL+"/functions/v1/notify-step",{method:"POST",headers:{"Content-Type":"application/json",apikey:SUPA_KEY,Authorization:"Bearer "+SUPA_KEY},body:JSON.stringify({to:a.email,subject:subj,html:html})}).then(r=>r.json()).then(res=>{if(res&&res.ok)toast("고객("+a.email+")에게 알림 발송 완료");else toast("발송 실패 · Supabase에 RESEND_API_KEY 설정 필요");}).catch(()=>toast("발송 오류"));}
function admWorkflow(id){const a=ADM_ROWS.find(x=>String(x.id)===String(id));if(!a){toast("불러오기 실패");return;}const wf=a.wf||{step:2};const step=wf.step;const stages=["문의","자료 공유","콘티 작성","콘티 컨펌","영상 제작","영상 컨펌","완료(리포트)"];const cur=stages[Math.min(step-1,6)];const u=wf.urls||{};var mat="";if(wf.dataUrl||wf.dataLink){mat='<div class="bg-g50 rounded-2xl p-3 mb-3 text-[13px]"><p class="font-bold text-g700 mb-1">고객 제출 자료</p>';if(wf.dataUrl)mat+='<button onclick="openLink(\''+esc(wf.dataUrl)+'\')" class="text-blue font-bold mr-3">파일 열기 \u2197</button>';if(wf.dataLink)mat+='<button onclick="openLink(\''+esc(wf.dataLink)+'\')" class="text-blue font-bold">링크 열기 \u2197</button>';mat+='</div>';}
let action="";
if(step<=2)action=`<div class="bg-g50 rounded-2xl p-4 text-[15px] text-g600">고객의 <b>자료 제출</b>을 기다리는 단계입니다.</div>`;
else if(step===3)action=`${mat}<p class="text-[14px] font-bold text-g700 mb-2">콘티 전달 (파일 또는 링크)</p>${wf.note?`<div class="bg-orange-50 rounded-2xl p-3 mb-2 text-[13px] text-orange-700">수정요청: ${esc(wf.note)}</div>`:""}<input id="admContiFile" type="file" class="block w-full text-[13px] text-g600 file:mr-3 file:py-2 file:px-3 file:rounded-xl file:border-0 file:bg-blue-tint file:text-blue file:font-bold file:cursor-pointer mb-2"><input id="admConti" placeholder="또는 콘티 링크 (드라이브/노션 등)" class="${INPUT} mb-2"><button onclick="admDeliverConti('${a.id}')" class="${BTN} w-full">콘티 전달하기 →</button>`;
else if(step===4)action=`<div class="text-center py-3"><div class="w-16 h-16 rounded-full bg-amber-50 grid place-items-center mx-auto mb-3"><i data-lucide="clock" class="w-8 h-8 text-amber-500"></i></div><p class="text-[22px] font-bold text-g900 mb-1.5">콘티를 전달했어요!</p><p class="text-[15px] text-g500">고객님의 컨펌을 기다리는 중이에요 ⏳</p></div>`;
else if(step===5)action=`<p class="text-[14px] font-bold text-g700 mb-2">영상 전달 (파일 또는 링크)</p>${wf.note?`<div class="bg-orange-50 rounded-2xl p-3 mb-2 text-[13px] text-orange-700">수정요청: ${esc(wf.note)}</div>`:""}<input id="admVideoFile" type="file" class="block w-full text-[13px] text-g600 file:mr-3 file:py-2 file:px-3 file:rounded-xl file:border-0 file:bg-blue-tint file:text-blue file:font-bold file:cursor-pointer mb-2"><input id="admVideo" placeholder="또는 영상 링크" class="${INPUT} mb-2"><button onclick="admDeliverVideo('${a.id}')" class="${BTN} w-full">영상 전달하기 →</button>`;
else if(step===6)action=`<div class="text-center py-3"><div class="w-16 h-16 rounded-full bg-amber-50 grid place-items-center mx-auto mb-3"><i data-lucide="clock" class="w-8 h-8 text-amber-500"></i></div><p class="text-[22px] font-bold text-g900 mb-1.5">영상을 전달했어요!</p><p class="text-[15px] text-g500">고객님의 컨펌을 기다리는 중이에요 ⏳</p></div>`;
else action=`<p class="text-[14px] font-bold text-g700 mb-2">업로드 URL 입력 (리포트 표기)</p><input id="admYt" placeholder="YouTube URL" value="${esc(u.yt||'')}" class="${INPUT} mb-2"><input id="admIg" placeholder="Instagram URL" value="${esc(u.ig||'')}" class="${INPUT} mb-2"><input id="admTt" placeholder="TikTok URL" value="${esc(u.tt||'')}" class="${INPUT} mb-2"><button onclick="admSaveUrls('${a.id}')" class="${BTN} w-full">업로드 URL 저장</button>`;
modal(`<div class="flex items-center justify-between mb-1"><h3 class="text-[19px] font-bold text-g900 break-all">${esc(a.brand_name)} 워크플로우</h3><button onclick="closeModal()" class="w-8 h-8 rounded-full bg-g100 grid place-items-center text-g500 flex-shrink-0">✕</button></div><p class="text-[14px] text-g500 mb-3">현재 단계: <b class="text-blue">${cur}</b></p><div class="space-y-2">${action}<button onclick="sendStepMail('${a.id}')" class="${BTN_GHOST} w-full"><i data-lucide="mail" class="w-4 h-4"></i>고객에게 진행 알림 메일 발송</button></div><div class="mt-3 pt-3 border-t border-g100"><p class="text-[13px] font-bold text-g600 mb-2">문의게시판</p><div class="space-y-2 max-h-40 overflow-y-auto mb-2">${(a.notes||[]).map(noteRow).join("")||'<p class="text-g400 text-[13px] text-center py-2">문의 없음</p>'}</div><textarea id="admNoteInput" rows="2" placeholder="답변 입력…" class="${INPUT} mb-2"></textarea><button onclick="admAddNote(\'${a.id}\')" class="${BTN_GHOST} w-full py-2 text-[13px]">답변 등록</button></div><button onclick="closeModal()" class="${BTN_GHOST} w-full mt-3">닫기</button>`);}
function admWfSave(id,patch,msg){const a=ADM_ROWS.find(x=>String(x.id)===String(id));const wf=Object.assign({},(a&&a.wf)||{step:2},patch);fetch(SUPA_URL+"/rest/v1/knollad_applications?id=eq."+id,{method:"PATCH",headers:Object.assign({"Content-Type":"application/json","Prefer":"return=minimal"},SH),body:JSON.stringify({wf})}).then(r=>{if(r.ok){if(a)a.wf=wf;toast(msg||"저장되었습니다");closeModal();loadApps();}else toast("저장 실패");}).catch(()=>toast("저장 오류"));}
function uploadToStorage(inputId,cb){const inp=document.getElementById(inputId);const f=inp&&inp.files&&inp.files[0];if(!f){cb(null);return;}const path=Date.now()+"_"+(f.name||"file").replace(/[^\w.\-]/g,"_");toast("파일 업로드 중…");fetch(SUPA_URL+"/storage/v1/object/deliverables/"+encodeURIComponent(path),{method:"POST",headers:{apikey:SUPA_KEY,Authorization:"Bearer "+SUPA_KEY,"Content-Type":f.type||"application/octet-stream","x-upsert":"true"},body:f}).then(r=>{if(r.ok)cb(SUPA_URL+"/storage/v1/object/public/deliverables/"+encodeURIComponent(path));else{toast("파일 업로드 실패");cb(null);}}).catch(()=>{toast("업로드 오류");cb(null);});}
function admDeliverConti(id){const title=(gv("admContiTitle")||"").trim();const text=(gv("admContiText")||"").trim();const link=(gv("admConti")||"").trim();const fi=document.getElementById("admContiFile");const hasF=fi&&fi.files&&fi.files.length;if(!title&&!text&&!link&&!hasF){toast("제목·내용·링크·파일 중 하나는 입력하세요");return;}const save=function(fu){admWfSave(id,{conti:{title:title||null,text:text||null,link:link||null,fileUrl:fu||null},step:4,note:null},"콘티가 전달되었습니다");};if(hasF){uploadToStorage("admContiFile",function(u){save(u);});}else save(null);}
function admDeliverVideo(id){const title=(gv("admVideoTitle")||"").trim();const text=(gv("admVideoText")||"").trim();const link=(gv("admVideo")||"").trim();const fi=document.getElementById("admVideoFile");const hasF=fi&&fi.files&&fi.files.length;if(!title&&!text&&!link&&!hasF){toast("제목·내용·링크·파일 중 하나는 입력하세요");return;}const save=function(fu){admWfSave(id,{video:{title:title||null,text:text||null,link:link||null,fileUrl:fu||null},step:6,note:null},"영상이 전달되었습니다");};if(hasF){uploadToStorage("admVideoFile",function(u){save(u);});}else save(null);}
function admSaveUrls(id){const urls={yt:(gv("admYt")||"").trim(),ig:(gv("admIg")||"").trim(),tt:(gv("admTt")||"").trim()};admWfSave(id,{urls,step:7},"업로드 URL이 저장되었습니다");}
function admSetPay(id,status){fetch(SUPA_URL+"/rest/v1/knollad_applications?id=eq."+id,{method:"PATCH",headers:Object.assign({"Content-Type":"application/json","Prefer":"return=minimal"},SH),body:JSON.stringify({pay_status:status})}).then(r=>{if(r.ok){toast("결제 상태: "+status);closeModal();loadApps();}else toast("처리 실패");}).catch(()=>toast("오류"));}
function admConfirmPay(id){fetch(SUPA_URL+"/rest/v1/knollad_applications?id=eq."+id,{method:"PATCH",headers:Object.assign({"Content-Type":"application/json","Prefer":"return=minimal"},SH),body:JSON.stringify({pay_status:"결제 완료"})}).then(r=>{if(r.ok){toast("결제 완료 처리됨");closeModal();loadApps();}else toast("처리 실패");}).catch(()=>toast("오류"));}
function selAdmWf(id){S.admWfId=id;render();window.scrollTo(0,0);}
function openAdmWf(id){S.admWfId=id;go("admin-workflow");}
function admWfStageBar(step){const st=["문의","자료","콘티작성","콘티컨펌","영상제작","영상컨펌","완료"];return `<div class="flex items-center gap-1 flex-wrap">${st.map((t,i)=>{const idx=i+1;const done=idx<step,act=idx===step;return `<span class="text-[12px] font-bold px-2.5 py-1 rounded-lg ${act?"bg-blue-tint text-blue":done?"bg-emerald-50 text-emerald-600":"bg-g100 text-g400"}">${t}</span>`+(i<6?'<span class="text-g300 text-[12px]">›</span>':"");}).join("")}</div>`;}
function admWfDetail(a){const wf=a.wf||{step:2};const step=wf.step;const u=wf.urls||{};const FI="block w-full text-[13px] text-g600 file:mr-3 file:py-2 file:px-3 file:rounded-xl file:border-0 file:bg-blue-tint file:text-blue file:font-bold file:cursor-pointer";
let action="";
if(step<=2)action=`<div class="text-center py-3"><div class="w-16 h-16 rounded-full bg-g100 grid place-items-center mx-auto mb-3"><i data-lucide="inbox" class="w-8 h-8 text-g500"></i></div><p class="text-[22px] font-bold text-g900 mb-1.5">고객님의 자료 제출을 기다리고 있어요</p><p class="text-[15px] text-g500">제출되면 콘티 작업을 시작할 수 있어요. 제출 내역은 아래 ‘진행 내역’에서 확인하세요.</p></div>`;
else if(step===3)action=`<p class="text-[16px] font-bold text-g900 mb-1">콘티 전달</p><p class="text-[13px] text-g500 mb-3">파일·링크가 없어도 제목·내용만으로 전달할 수 있어요.</p>${wf.note?`<div class="bg-orange-50 rounded-2xl p-3 mb-2 text-[13px] text-orange-700">고객 수정요청: ${esc(wf.note)}</div>`:""}<input id="admContiTitle" placeholder="제목 (예: 1차 콘티)" class="${INPUT} mb-2"><textarea id="admContiText" rows="6" placeholder="콘티 내용을 자유롭게 작성하세요" class="${INPUT} resize-none text-[16px] mb-2"></textarea><input id="admContiFile" type="file" class="${FI} mb-2"><input id="admConti" placeholder="참고 링크 (선택)" class="${INPUT} mb-3"><button onclick="admDeliverConti('${a.id}')" class="${BTN} w-full">콘티 전달하기 →</button>`;
else if(step===4)action=`<div class="text-center py-3"><div class="w-16 h-16 rounded-full bg-amber-50 grid place-items-center mx-auto mb-3"><i data-lucide="clock" class="w-8 h-8 text-amber-500"></i></div><p class="text-[22px] font-bold text-g900 mb-1.5">콘티를 전달했어요!</p><p class="text-[15px] text-g500">고객님의 컨펌을 기다리는 중이에요 ⏳</p></div>`;
else if(step===5)action=`<p class="text-[16px] font-bold text-g900 mb-1">영상 전달</p><p class="text-[13px] text-g500 mb-3">파일·링크가 없어도 제목·내용만으로 전달할 수 있어요.</p>${wf.note?`<div class="bg-orange-50 rounded-2xl p-3 mb-2 text-[13px] text-orange-700">고객 수정요청: ${esc(wf.note)}</div>`:""}<input id="admVideoTitle" placeholder="제목 (예: 1차 편집본)" class="${INPUT} mb-2"><textarea id="admVideoText" rows="6" placeholder="영상 관련 내용을 자유롭게 작성하세요" class="${INPUT} resize-none text-[16px] mb-2"></textarea><input id="admVideoFile" type="file" class="${FI} mb-2"><input id="admVideo" placeholder="참고 링크 (선택)" class="${INPUT} mb-3"><button onclick="admDeliverVideo('${a.id}')" class="${BTN} w-full">영상 전달하기 →</button>`;
else if(step===6)action=`<div class="text-center py-3"><div class="w-16 h-16 rounded-full bg-amber-50 grid place-items-center mx-auto mb-3"><i data-lucide="clock" class="w-8 h-8 text-amber-500"></i></div><p class="text-[22px] font-bold text-g900 mb-1.5">영상을 전달했어요!</p><p class="text-[15px] text-g500">고객님의 컨펌을 기다리는 중이에요 ⏳</p></div>`;
else action=`<p class="text-[15px] font-bold text-g900 mb-2">업로드 URL 입력 (리포트 자동 표기)</p><input id="admYt" placeholder="YouTube URL" value="${esc(u.yt||'')}" class="${INPUT} mb-2"><input id="admIg" placeholder="Instagram URL" value="${esc(u.ig||'')}" class="${INPUT} mb-2"><input id="admTt" placeholder="TikTok URL" value="${esc(u.tt||'')}" class="${INPUT} mb-3"><button onclick="admSaveUrls('${a.id}')" class="${BTN} w-full">업로드 URL 저장</button>`;
markSeen(a,"adm");const notes=a.notes||[];
return `<div class="${CARD} p-6"><div class="flex items-center justify-between mb-4 flex-wrap gap-2"><div class="min-w-0"><h2 class="text-[20px] font-bold text-g900 truncate">${esc(a.brand_name)}</h2><p class="text-[13px] text-g500 truncate">${esc(a.email)}${a.contact_name?" · "+esc(a.contact_name):""} · 결제 ${esc(a.pay_status||"대기중")}</p></div><button onclick="sendStepMail('${a.id}')" class="${BTN_GHOST} px-4 py-2.5 text-[13px] flex-shrink-0"><i data-lucide="mail" class="w-4 h-4"></i>고객 알림</button></div>${wfStepper(step)}</div>
<div class="${CARD} p-6 border-2 border-blue"><div class="flex items-center gap-2 mb-3"><span class="w-2 h-2 rounded-full bg-blue"></span><h3 class="text-[18px] font-bold text-g900">현재 진행 상황</h3></div>${action}</div>
<div class="${CARD} p-6"><h3 class="text-[16px] font-bold text-g900 mb-4">진행 내역 · 주고받은 자료</h3>${wfActivityFeed(a)}</div>
<div class="${CARD} p-6"><h3 class="text-[16px] font-bold text-g900 mb-3">메시지 · 고객 소통</h3><div class="space-y-2 max-h-[42vh] overflow-y-auto mb-3 pr-1">${notes.length?notes.map(noteRow).join(""):'<p class="text-g400 text-center py-6 text-[14px]">대화가 없습니다.</p>'}</div><textarea id="admMsgInput" rows="2" placeholder="메시지 입력…" class="${INPUT} resize-none mb-2"></textarea><button onclick="admWfMsg('${a.id}')" class="${BTN} w-full py-3">보내기</button></div>`;}
function viewAdminWorkflow(){if(!ADM_ROWS.length)setTimeout(loadApps,30);const camps=ADM_ROWS.filter(a=>a.status==="승인 완료");if((!S.admWfId||!camps.find(c=>String(c.id)===String(S.admWfId)))&&camps.length)S.admWfId=camps[0].id;const a=camps.find(x=>String(x.id)===String(S.admWfId));
const st=["문의","자료","콘티작성","콘티컨펌","영상제작","영상컨펌","완료"];
const list=camps.length?camps.map(c=>{const wf=c.wf||{step:2};const sel=a&&String(a.id)===String(c.id);return `<button onclick="selAdmWf('${c.id}')" class="w-full text-left p-3 rounded-2xl mb-1 ${sel?"bg-blue-tint":"hover:bg-g50"}"><div class="flex items-center justify-between gap-2"><span class="font-bold text-g900 text-[15px] truncate">${esc(c.brand_name)}</span><span class="text-[11px] font-bold px-2 py-0.5 rounded-md ${sel?"text-blue bg-white":"bg-g100 text-g500"}">${st[Math.min(wf.step-1,6)]}</span></div><p class="text-[12px] text-g400 truncate mt-0.5">${esc(c.email)}</p></button>`;}).join(""):'<p class="text-g400 text-center py-8 text-[14px]">승인된 캠페인이 없습니다.</p>';
return `<div class="p-8 md:p-10">${pageHeader("WORKFLOW","워크플로우 관리","캠페인을 선택해 단계를 진행하고 고객과 소통하세요")}
<div class="grid lg:grid-cols-3 gap-5"><div class="${CARD} p-3 self-start lg:sticky lg:top-6"><p class="text-[12px] font-bold text-g400 px-2 py-1 tracking-widest">승인 캠페인 ${camps.length}건</p>${list}</div>
<div class="lg:col-span-2 space-y-4">${a?admWfDetail(a):`<div class="${CARD} p-12 text-center text-g500 text-[16px]">왼쪽에서 캠페인을 선택하세요.</div>`}</div></div></div>`;}
function viewAdminCalendar(){if(!ADM_ROWS.length)setTimeout(loadApps,30);const nd=new Date();if(S.calY==null){S.calY=nd.getFullYear();S.calM=nd.getMonth();}const y=S.calY,m=S.calM;
const startDow=new Date(y,m,1).getDay();const days=new Date(y,m+1,0).getDate();const todayStr=`${nd.getFullYear()}-${String(nd.getMonth()+1).padStart(2,'0')}-${String(nd.getDate()).padStart(2,'0')}`;
const ev=[];ADM_ROWS.forEach(a=>{if(a.status==="승인 완료"&&a.preferred_date)ev.push({date:a.preferred_date,title:(a.brand_name||"")+" 업로드",type:"auto"});(a.schedule||[]).forEach(e=>{if(e&&e.date)ev.push({date:e.date,title:(a.brand_name?a.brand_name+" · ":"")+(e.title||""),type:"manual"});});});
let cells="";for(let i=0;i<startDow;i++)cells+='<div></div>';
for(let d=1;d<=days;d++){const ds=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;const isT=ds===todayStr;const es=ev.filter(e=>e.date===ds);
cells+=`<div class="min-h-[120px] md:min-h-[140px] border ${isT?"border-blue bg-blue-soft":"border-g100"} rounded-2xl p-2.5"><div class="text-[15px] font-bold ${isT?"text-blue":"text-g500"} mb-1">${d}</div>${es.map(e=>`<div title="${esc(e.title)}" class="mb-1 text-[12px] px-2 py-1 rounded-lg ${e.type==="auto"?"bg-blue-tint text-blue":"bg-emerald-50 text-emerald-700"} truncate font-bold">${esc(e.title)}</div>`).join("")}</div>`;}
const total=ev.length;
return `<div class="p-8 md:p-10">${pageHeader("SCHEDULE","캠페인 일정","전체 회원의 업로드 예정일과 회원이 등록한 일정을 한눈에 확인합니다")}
<div class="${CARD} p-6 md:p-8"><div class="flex items-center justify-between mb-5"><button onclick="calPrev()" class="w-10 h-10 rounded-full bg-g100 grid place-items-center text-g600 hover:bg-g200 text-[18px] font-bold">‹</button><h2 class="text-[22px] font-bold text-g900">${y}년 ${m+1}월</h2><button onclick="calNext()" class="w-10 h-10 rounded-full bg-g100 grid place-items-center text-g600 hover:bg-g200 text-[18px] font-bold">›</button></div>
<div class="grid grid-cols-7 gap-2 mb-2 text-center text-[14px] font-bold text-g400">${["일","월","화","수","목","금","토"].map(d=>`<div>${d}</div>`).join("")}</div>
<div class="grid grid-cols-7 gap-2">${cells}</div>
<div class="flex gap-4 mt-5 text-[13px] text-g500 flex-wrap"><span class="inline-flex items-center gap-1.5"><span class="w-3 h-3 rounded bg-blue-tint"></span>업로드 예정 (신청값)</span><span class="inline-flex items-center gap-1.5"><span class="w-3 h-3 rounded bg-emerald-50 border border-emerald-200"></span>회원이 추가한 일정</span><span class="ml-auto text-g400">이번 달 일정 ${ev.filter(e=>e.date&&e.date.slice(0,7)===`${y}-${String(m+1).padStart(2,'0')}`).length}건</span></div></div></div>`;}
function buildTasks(){const list=[];if(S.role==="customer"){(S.myCamps||[]).forEach(function(c){if(c.status!=="승인 완료")return;const wf=wfOf(c);const u=unreadCount(c,"cust");const bn=c.brand_name||"캠페인";if(wf.step===2)list.push({id:c.id,brand:bn,text:"소재·자료를 제출해야 합니다",act:"workflow",urgent:true});else if(wf.step===4)list.push({id:c.id,brand:bn,text:"크놀AD가 보낸 콘티를 컨펌(또는 수정요청)해야 합니다",act:"workflow",urgent:true});else if(wf.step===6)list.push({id:c.id,brand:bn,text:"크놀AD가 보낸 영상을 컨펌(또는 수정요청)해야 합니다",act:"workflow",urgent:true});else if(wf.step>=7&&c.pay_status!=="결제 완료")list.push({id:c.id,brand:bn,text:"결제(정산)를 진행해야 합니다",act:"settlement"});if(u>0)list.push({id:c.id,brand:bn,text:"크놀AD의 새 메시지 "+u+"건이 있습니다",act:"workflow",msg:true});});}else if(S.role==="admin"){(ADM_ROWS||[]).forEach(function(c){if(c.status!=="승인 완료")return;const wf=c.wf||{step:2};const u=unreadCount(c,"adm");const bn=c.brand_name||"고객";const nm=c.contact_name||bn;if(wf.step===3)list.push({id:c.id,brand:bn,text:nm+" 고객님에게 콘티를 제출(전달)해야 합니다",act:"admwf",urgent:true});else if(wf.step===5)list.push({id:c.id,brand:bn,text:nm+" 고객님에게 영상을 제출(전달)해야 합니다",act:"admwf",urgent:true});else if(wf.step>=7&&!((wf.urls||{}).yt||(wf.urls||{}).ig||(wf.urls||{}).tt))list.push({id:c.id,brand:bn,text:bn+" 업로드 URL을 입력해야 합니다",act:"admwf",urgent:true});if(u>0)list.push({id:c.id,brand:bn,text:nm+" 고객님의 새 메시지 "+u+"건",act:"admwf",msg:true});});}return list;}
function taskRow(x){return `<button onclick="goTask('${x.id}','${x.act}')" class="w-full text-left flex items-center gap-3 p-3.5 rounded-2xl border border-g100 hover:border-blue hover:bg-blue-soft transition-colors mb-2"><div class="w-10 h-10 rounded-full grid place-items-center flex-shrink-0 ${x.msg?"bg-violet-50 text-violet-600":x.urgent?"bg-red-50 text-red-500":"bg-blue-tint text-blue"}"><i data-lucide="${x.msg?"message-circle":x.urgent?"alert-circle":"circle-dot"}" class="w-5 h-5"></i></div><div class="flex-1 min-w-0"><p class="text-[15px] font-bold text-g900 truncate">${esc(x.brand)}</p><p class="text-[14px] text-g600">${esc(x.text)}</p></div><i data-lucide="chevron-right" class="w-5 h-5 text-g300 flex-shrink-0"></i></button>`;}
function goTask(id,act){closeModal();if(S.role==="admin"){openAdmWf(id);return;}var a=(S.myCamps||[]).find(function(x){return String(x.id)===String(id);});if(a)S.activeCamp=a;go(act==="settlement"?"settlement":"workflow");}
function openTodo(){const t=buildTasks();modal(`<div class="flex items-center justify-between mb-4"><h3 class="text-[20px] font-bold text-g900">해야 할 일${t.length?` <span class="text-blue">${t.length}</span>`:""}</h3><button onclick="closeModal()" class="w-8 h-8 rounded-full bg-g100 grid place-items-center text-g500">✕</button></div><div class="max-h-[62vh] overflow-y-auto">${t.length?t.map(taskRow).join(""):'<div class="text-center py-10"><i data-lucide="check-circle-2" class="w-12 h-12 text-emerald-400 mx-auto mb-2"></i><p class="text-g500 text-[15px]">지금 처리할 일이 없습니다</p></div>'}</div>`);}
function viewTodo(){if(S.role==="admin"){if(!ADM_ROWS.length)setTimeout(loadApps,30);}else setTimeout(loadMyCamps,30);const t=buildTasks();return `<div class="p-8 md:p-10"><div class="max-w-3xl">${pageHeader("TO-DO","해야 할 일","지금 처리해야 할 작업을 한눈에 확인하고 바로 이동하세요")}<div class="${CARD} p-6">${t.length?t.map(taskRow).join(""):'<div class="text-center py-16"><i data-lucide="check-circle-2" class="w-14 h-14 text-emerald-400 mx-auto mb-3"></i><p class="text-g600 text-[17px] font-bold">지금 처리할 일이 없습니다</p><p class="text-g400 text-[14px] mt-1">상대방의 작업을 기다리는 중이거나 모두 완료됐어요.</p></div>'}</div></div></div>`;}
function showCreds(email,pw){CRED_MSG="[크놀AD] 캠페인 신청이 승인되었습니다.\n\n■ 로그인 정보\n- 아이디(이메일): "+email+"\n- 비밀번호: "+pw+"\n- 로그인: https://cnolad.vercel.app  (로그인)\n\n승인된 계정으로 로그인하시면 채널 선택, 단가 확인, 자료 업로드, 컨펌, 업로드 일정, 리포트까지 실시간으로 확인하실 수 있습니다.\n감사합니다. 에이치알컴퍼니(주) 드림";
modal(`<div class="text-center"><div class="w-14 h-14 rounded-full bg-blue-tint grid place-items-center mx-auto mb-4"><i data-lucide="key-round" class="w-7 h-7 text-blue"></i></div><h3 class="text-[20px] font-bold text-g900 mb-1">계정 발급 완료</h3><p class="text-g500 text-[14px] mb-4">아래 안내문을 복사해 고객에게 전달하세요.</p></div>
<div class="bg-g50 rounded-[20px] p-4 space-y-2 text-[15px] mb-3"><div class="flex justify-between gap-3"><span class="text-g500">아이디</span><span class="font-bold text-g900 break-all text-right">${esc(email)}</span></div><div class="flex justify-between gap-3"><span class="text-g500">비밀번호</span><span class="font-bold text-blue num">${esc(pw)}</span></div></div>
<div class="bg-blue-soft rounded-[20px] p-4 text-[13px] text-g700 whitespace-pre-line max-h-40 overflow-y-auto mb-3">${esc(CRED_MSG)}</div>
<div class="flex gap-2"><button onclick="copyText(CRED_MSG)" class="${BTN} flex-1"><i data-lucide="copy" class="w-4 h-4"></i>승인 안내문 복사</button><button onclick="closeModal()" class="${BTN_GHOST} px-5">닫기</button></div>`);}
function memberCampaigns(email){const rows=ADM_ROWS.filter(a=>a.email===email);const items=rows.map(a=>`<div class="bg-g50 rounded-2xl p-3"><div class="flex items-center justify-between gap-3"><div class="min-w-0"><p class="font-bold text-g900">${esc(a.brand_name)}</p><p class="text-[12px] text-g500 truncate">${(a.created_at||"").slice(0,10)} · ${(a.channels||[]).map(c=>c.name).join(", ")||"-"} · ${wonM(a.total_amount||0)}</p></div>${statusBadge(a.status)}</div>${a.status==="승인 완료"?`<button onclick="closeModal();openAdmWf('${a.id}')" class="${BTN} w-full mt-2.5 py-2.5 text-[13px]"><i data-lucide="list-checks" class="w-4 h-4"></i>워크플로우 · 콘티/영상 전달</button>`:""}</div>`).join("");modal(`<div class="flex items-center justify-between mb-1"><h3 class="text-[19px] font-bold text-g900 break-all">${esc(email)}</h3><button onclick="closeModal()" class="w-8 h-8 rounded-full bg-g100 grid place-items-center text-g500 flex-shrink-0">✕</button></div><p class="text-[14px] text-g500 mb-4">신청 ${rows.length}건</p><div class="space-y-2 max-h-[55vh] overflow-y-auto">${items||'<p class="text-g400 text-center py-6">신청 내역이 없습니다.</p>'}</div><button onclick="closeModal()" class="${BTN} w-full mt-4">닫기</button>`);}
function addChannelByHandle(){const el=document.getElementById("newHandle");let h=((el?el.value:"")||"").trim().replace(/^@/,"");if(!h){toast("핸들을 입력해주세요");return;}toast("채널 정보를 불러오는 중…");fetch("https://www.googleapis.com/youtube/v3/channels?part=snippet,statistics&forHandle="+encodeURIComponent(h)+"&fields=items(id,snippet/title,snippet/thumbnails/medium/url,statistics/subscriberCount,statistics/viewCount,statistics/videoCount)&key="+YT_API_KEY).then(r=>r.json()).then(res=>{const it=(res.items||[])[0];if(!it){toast("채널을 찾을 수 없습니다");return;}if(CH.find(c=>c.id===it.id)){toast("이미 등록된 채널입니다");return;}const st=it.statistics||{},sn=it.snippet||{};CH.push({id:it.id,name:sn.title||h,read:null,region:"KR",plat:["YouTube"],handle:h,yt:+st.subscriberCount||0,views:+st.viewCount||0,vids:+st.videoCount||0,ig:null,tt:null,prod:65,pub:30,logo:(sn.thumbnails&&sn.thumbnails.medium)?sn.thumbnails.medium.url:null});toast("추가됨: "+(sn.title||h));render();}).catch(()=>toast("불러오기 실패"));}
function viewAdminChannels(){return `<div class="p-8 md:p-10">${pageHeader("CHANNEL DB","채널 관리",`총 ${CH.length}개 채널 · 핸들로 채널을 추가할 수 있습니다`)}<div class="${CARD} p-5 mb-4 flex items-center gap-3 flex-wrap"><div class="flex-1 min-w-[220px]"><input id="newHandle" placeholder="유튜브 핸들 입력 (예: mimtube777)" class="${INPUT}" onkeydown="if(event.key==='Enter')addChannelByHandle()"></div><button onclick="addChannelByHandle()" class="${BTN} px-6"><i data-lucide="plus" class="w-4 h-4"></i>채널 추가</button></div><div class="${CARD} overflow-hidden"><div class="overflow-x-auto"><table class="w-full text-[14px] min-w-[820px]"><thead><tr class="border-b border-g100 bg-g50">${["채널","플랫폼","구독자(YT)","총 조회수","평균","제작+발행","단순발행","공개"].map(h=>`<th class="px-5 py-3.5 text-left text-[13px] font-bold text-g500 whitespace-nowrap">${h}</th>`).join("")}</tr></thead><tbody>${CH.map(c=>`<tr class="border-b border-g100 last:border-0 hover:bg-g50"><td class="px-5 py-3"><div class="flex items-center gap-3">${logoEl(c,"w-8 h-8 text-sm")}<div><p class="font-bold text-g900">${esc(c.name)}</p><p class="text-[13px] text-g400">${REGION_LABEL[c.region]}${c.read?" · "+esc(c.read):""}</p></div></div></td><td class="px-5 py-3"><div class="flex gap-1 flex-wrap">${c.plat.map(platBadge).join("")}</div></td><td class="px-5 py-3 text-g600 num">${fmtSub(c.yt)}</td><td class="px-5 py-3 text-g600 num">${fmtView(c.views)}</td><td class="px-5 py-3 text-g600 num">${fmtView(avgView(c))}</td><td class="px-5 py-3 font-bold text-g900 num">${c.prod}만</td><td class="px-5 py-3 font-bold text-g900 num">${c.pub}만</td><td class="px-5 py-3"><button onclick="this.querySelector('span').classList.toggle('translate-x-[18px]');this.classList.toggle('bg-blue');this.classList.toggle('bg-g300')" class="relative inline-flex h-5 w-9 items-center rounded-full bg-blue transition-colors"><span class="inline-block w-3.5 h-3.5 rounded-full bg-white shadow-sm transform transition-transform translate-x-[18px]"></span></button></td></tr>`).join("")}</tbody></table></div></div></div>`;}
function viewAdminMembers(){setTimeout(loadApps,30);setTimeout(loadMembersList,40);return `<div class="p-8 md:p-10">${pageHeader("MEMBER DB","회원DB","회사/브랜드별 신청 고객 · 행을 클릭하면 캠페인 내역을 볼 수 있습니다")}<div class="flex justify-end mb-4"><button onclick="exportMembersCSV()" class="${BTN} px-5 py-2.5 text-[14px]"><i data-lucide="download" class="w-4 h-4"></i>엑셀 다운로드</button></div>
<div class="${CARD} overflow-hidden"><div class="overflow-x-auto"><table class="w-full text-left min-w-[860px]"><thead><tr class="border-b border-g100 bg-g50">${["담당자","아이디(이메일)","회사/브랜드","연락처","신청 건수","상태","계정"].map(h=>`<th class="px-4 py-3 text-[13px] font-bold text-g500 whitespace-nowrap">${h}</th>`).join("")}</tr></thead><tbody id="memRows"><tr><td colspan="7" class="px-4 py-10 text-center text-g400">불러오는 중…</td></tr></tbody></table></div></div></div>`;}
function exportMembersCSV(){const map={};ADM_ROWS.forEach(a=>{const k=a.email;if(!map[k])map[k]={name:a.contact_name,email:a.email,phone:a.phone,brand:a.brand_name,count:0,last:a.status,pw:a.account_pw};map[k].count++;map[k].brand=a.brand_name;if(a.account_pw)map[k].pw=a.account_pw;if(a.status==="승인 완료")map[k].last="승인 완료";});const list=Object.values(map);if(!list.length){toast("내보낼 회원이 없습니다");return;}const q=v=>'"'+String(v==null?"":v).replace(/"/g,'""')+'"';const head=["담당자","아이디(이메일)","회사/브랜드","연락처","신청건수","상태","비밀번호"];const rows=list.map(m=>[m.name,m.email,m.brand,m.phone,m.count,m.last,m.pw||""].map(q).join(","));const csv="﻿"+head.map(q).join(",")+"\n"+rows.join("\n");const blob=new Blob([csv],{type:"text/csv;charset=utf-8;"});const url=URL.createObjectURL(blob);const el=document.createElement("a");el.href=url;el.download="크놀AD_회원DB_"+new Date().toISOString().slice(0,10)+".csv";document.body.appendChild(el);el.click();document.body.removeChild(el);URL.revokeObjectURL(url);toast("엑셀(CSV) 다운로드 완료");}
function loadMembersList(){fetch(SUPA_URL+"/rest/v1/knollad_members?select=*&order=created_at.desc",{headers:SH}).then(r=>r.json()).then(rows=>{S.members=Array.isArray(rows)?rows:[];if(S.view==="admin-members")renderMembers();}).catch(()=>{});}
function renderMembers(){const b=document.getElementById("memRows");if(!b)return;const list=(S.members||[]).map(m=>{const camps=ADM_ROWS.filter(a=>a.email===m.email);return {name:m.contact_name,email:m.email,phone:(camps[0]||{}).phone||"",brand:m.brand_name,count:camps.length,last:camps.some(a=>a.status==="승인 완료")?"승인 완료":((camps[0]||{}).status||"승인 완료"),pw:m.password};});
b.innerHTML=list.length?list.map(m=>`<tr class="border-b border-g100 last:border-0 hover:bg-g50 cursor-pointer" onclick="memberCampaigns('${esc(m.email)}')"><td class="px-4 py-3 font-bold text-g900 text-[15px]">${esc(m.name)}</td><td class="px-4 py-3 text-g600 text-[14px]">${esc(m.email)}</td><td class="px-4 py-3 text-g700 text-[14px] font-bold">${esc(m.brand)}</td><td class="px-4 py-3 text-g600 num text-[14px]">${esc(m.phone)}</td><td class="px-4 py-3 num text-[14px]">${m.count}건</td><td class="px-4 py-3">${statusBadge(m.last)}</td><td class="px-4 py-3">${m.pw?`<button onclick="event.stopPropagation();showCreds('${esc(m.email)}','${esc(m.pw)}')" class="text-[13px] text-blue font-bold">안내문 복사</button>`:'<span class="text-g300 text-[13px]">미발급</span>'}</td></tr>`).join(""):'<tr><td colspan="7" class="px-4 py-10 text-center text-g400">회원이 없습니다.</td></tr>';}

function loadSettings(){fetch(SUPA_URL+"/rest/v1/knollad_settings?id=eq.1&select=*",{headers:SH}).then(r=>r.json()).then(rows=>{S.notify=(rows&&rows[0])||{notify_on:false,notify_email:null};if(S.view==="admin-dashboard")renderNotifySettings();}).catch(()=>{});}
function notifyStep(camp,stepLabel,who){const n=S.notify;if(!n||!n.notify_on||!n.notify_email)return;const bn=(camp&&camp.brand_name)||"캠페인";const subj="[크놀AD] "+bn+" · "+stepLabel;const html="<div style=\"font-family:sans-serif\">캠페인 <b>"+esc(bn)+"</b> 워크플로우가 진행되었습니다.<br><br>단계: <b>"+esc(stepLabel)+"</b><br>처리: "+esc(who||"")+"<br>시각: "+new Date().toLocaleString("ko-KR")+"</div>";fetch(SUPA_URL+"/functions/v1/notify-step",{method:"POST",headers:{"Content-Type":"application/json",apikey:SUPA_KEY,Authorization:"Bearer "+SUPA_KEY},body:JSON.stringify({to:n.notify_email,subject:subj,html:html})}).catch(()=>{});}
function renderNotifySettings(){const el=document.getElementById("notifySettings");if(!el)return;const n=S.notify||{notify_on:false,notify_email:""};el.innerHTML=`<div class="${CARD} p-5 flex items-center gap-4 flex-wrap"><div class="flex items-center gap-3 flex-1 min-w-[220px]"><div class="w-10 h-10 rounded-2xl bg-blue-tint grid place-items-center flex-shrink-0"><i data-lucide="mail" class="w-5 h-5 text-blue"></i></div><div><p class="text-[15px] font-bold text-g900">워크플로우 단계 알림 이메일</p><p class="text-[13px] text-g500">단계가 진행될 때마다 입력한 이메일로 자동 알림을 보냅니다.</p></div></div><input id="notifyEmail" value="${esc(n.notify_email||"")}" placeholder="alert@company.com" class="${INPUT} max-w-[240px]"><button onclick="saveNotify(${n.notify_on?"false":"true"})" class="px-5 py-3 rounded-2xl text-white font-bold text-[14px] flex-shrink-0 ${n.notify_on?"bg-emerald-500":"bg-g400"}">${n.notify_on?"알림 ON · 켜짐":"알림 OFF · 꺼짐"}</button></div>`;if(window.lucide)lucide.createIcons();}
function saveNotify(on){const email=(gv("notifyEmail")||"").trim();fetch(SUPA_URL+"/rest/v1/knollad_settings?id=eq.1",{method:"PATCH",headers:Object.assign({"Content-Type":"application/json","Prefer":"return=minimal"},SH),body:JSON.stringify({notify_on:!!on,notify_email:email||null})}).then(r=>{if(r.ok){S.notify={notify_on:!!on,notify_email:email||null};toast(on?"단계 알림 ON · 저장됨":"단계 알림 OFF · 저장됨");renderNotifySettings();}else toast("저장 실패");}).catch(()=>toast("오류"));}
function noteRow(nt){const me=(S.role==="admin")?(nt.role==="knoll"||nt.who==="크놀AD"):(nt.role==="cust"||nt.who==="고객"||(S.cust&&nt.who===S.cust.name));return `<div class="flex ${me?"justify-end":"justify-start"}"><div class="max-w-[88%] rounded-2xl px-4 py-3 ${me?"text-white":"bg-g100 text-g800"}" ${me?'style="background:#3182F6"':''}><p class="text-[12px] font-bold ${me?"text-white/85":"text-g500"} mb-1">${esc(nt.who)} · ${(nt.at||"").slice(0,16).replace("T"," ")}</p>${nt.title?`<p class="text-[16px] font-bold mb-1">${esc(nt.title)}</p>`:""}${nt.text?`<p class="text-[16px] whitespace-pre-wrap leading-relaxed">${esc(nt.text)}</p>`:""}${(nt.fileUrl||nt.link)?`<div class="mt-2 flex gap-3">${nt.fileUrl?`<button onclick="openLink(\'${esc(nt.fileUrl)}\')" class="text-[13px] font-bold underline ${me?"text-white":"text-blue"}">첨부파일 ↗</button>`:""}${nt.link?`<button onclick="openLink(\'${esc(nt.link)}\')" class="text-[13px] font-bold underline ${me?"text-white":"text-blue"}">링크 ↗</button>`:""}</div>`:""}</div></div>`;}
function viewNotes(){setTimeout(loadMyCamps,30);const c=S.activeCamp;if(!c)return `<div class="p-8 md:p-10">${pageHeader("BOARD","문의게시판")}<div class="${CARD} p-12 text-center text-g500 text-[16px]">캠페인을 선택하면 문의를 남길 수 있습니다.<br>‘캠페인 관리’에서 캠페인을 선택하세요.</div></div>`;markSeen(c,"cust");const notes=c.notes||[];
return `<div class="p-8 md:p-10"><div class="max-w-2xl">${pageHeader("BOARD","문의게시판",esc(c.brand_name)+" 캠페인 관련 문의를 남기면 크놀AD가 답변해 드립니다")}
<div class="${CARD} p-6 md:p-7 mb-4">${field('제목 <span class="text-blue">*</span>',`<input id="noteTitle" placeholder="문의 제목을 짧게 적어주세요" class="${INPUT}">`)}<div class="mt-4">${field('내용 <span class="text-blue">*</span>',`<textarea id="noteInput" rows="7" placeholder="문의하실 내용을 자유롭게 적어주세요." class="${INPUT} resize-none"></textarea>`)}</div><div class="mt-4">${field('첨부 파일 (선택)',uploadZone("noteFile","전달하실 파일이 있다면 업로드"))}</div><div class="mt-3">${field('참고 링크 (선택)',`<input id="noteLink" placeholder="https:// 또는 드라이브 링크" class="${INPUT}">`)}</div><button onclick="addNote()" class="${BTN} w-full mt-5 py-4">문의 등록</button></div>
<div class="${CARD} p-6"><h3 class="text-[16px] font-bold text-g900 mb-4">문의 내역</h3><div class="space-y-3 max-h-[55vh] overflow-y-auto pr-1">${notes.length?notes.map(noteRow).join(""):'<p class="text-g400 text-center py-10 text-[15px]">아직 문의가 없습니다. 위에서 첫 문의를 남겨보세요.</p>'}</div></div></div></div>`;}
function addNote(){const c=S.activeCamp;if(!c){toast("캠페인을 선택하세요");return;}const title=(gv("noteTitle")||"").trim();const text=(gv("noteInput")||"").trim();const link=(gv("noteLink")||"").trim();if(!title&&!text){toast("제목과 내용을 입력하세요");return;}const fi=document.getElementById("noteFile");const post=function(fileUrl){const notes=(c.notes||[]).slice();notes.push({who:(S.cust&&S.cust.name)||"고객",role:"cust",title:title||null,text:text,link:link||null,fileUrl:fileUrl||null,at:new Date().toISOString()});c.notes=notes;fetch(SUPA_URL+"/rest/v1/knollad_applications?id=eq."+c.id,{method:"PATCH",headers:Object.assign({"Content-Type":"application/json","Prefer":"return=minimal"},SH),body:JSON.stringify({notes:notes})}).then(r=>{if(!r.ok)toast("저장 실패");}).catch(()=>toast("저장 오류"));toast("문의가 등록되었습니다");render();};if(fi&&fi.files&&fi.files.length){uploadToStorage("noteFile",function(url){post(url);});}else{post(null);}}
function admAddNote(id){const a=ADM_ROWS.find(x=>String(x.id)===String(id));if(!a)return;const title=(gv("admNoteTitle")||"").trim();const text=(gv("admNoteInput")||"").trim();const link=(gv("admNoteLink")||"").trim();if(!title&&!text){toast("내용을 입력하세요");return;}const fi=document.getElementById("admNoteFile");const post=function(fileUrl){const notes=(a.notes||[]).slice();notes.push({who:"크놀AD",role:"knoll",title:title||null,text:text,link:link||null,fileUrl:fileUrl||null,at:new Date().toISOString()});a.notes=notes;fetch(SUPA_URL+"/rest/v1/knollad_applications?id=eq."+id,{method:"PATCH",headers:Object.assign({"Content-Type":"application/json","Prefer":"return=minimal"},SH),body:JSON.stringify({notes:notes})}).then(r=>{if(r.ok){toast("답변 등록됨");loadApps();}else toast("저장 실패");}).catch(()=>toast("오류"));};if(fi&&fi.files&&fi.files.length){uploadToStorage("admNoteFile",function(url){post(url);});}else{post(null);}}
/* ===== LIVE ===== */
let _liveDone=false,_liveTried=false;
function maybeLiveRefresh(){
  if(_liveDone||_liveTried)return;_liveTried=true;
  const ids=CH.map(c=>c.id);
  fetch(`https://www.googleapis.com/youtube/v3/channels?part=snippet,statistics&id=${ids.join(",")}&fields=items(id,snippet/thumbnails/medium/url,statistics/subscriberCount,statistics/viewCount,statistics/videoCount)&key=${YT_API_KEY}`)
  .then(r=>r.json()).then(res=>{(res.items||[]).forEach(it=>{const c=CH.find(x=>x.id===it.id);if(!c)return;if(it.snippet&&it.snippet.thumbnails&&it.snippet.thumbnails.medium)c.logo=it.snippet.thumbnails.medium.url;if(it.statistics){c.yt=+it.statistics.subscriberCount;c.views=+it.statistics.viewCount;c.vids=+it.statistics.videoCount;}});
    _liveDone=true;
    if(S.view==="channel-picker"||S.view==="cust-channels")updateTable();
    else if(document.getElementById("selBox")){document.getElementById("selBox").innerHTML=SEL.size?selectedSummary():'';if(window.lucide)lucide.createIcons();}
  }).catch(()=>{_liveTried=false;});
}
function toast(msg){let t=document.getElementById("toast");if(!t){t=document.createElement("div");t.id="toast";t.className="fixed bottom-8 left-1/2 z-[400] px-5 py-3 rounded-[20px] text-[15px] font-bold transition-all";t.style.background="#191F28";t.style.color="#ffffff";t.style.boxShadow="0 16px 50px rgba(17,24,39,0.22)";t.style.opacity=0;document.body.appendChild(t);}t.textContent=msg;t.style.background="#191F28";t.style.color="#ffffff";t.style.transform="translateX(-50%) translateY(0)";t.style.opacity=1;clearTimeout(t._t);t._t=setTimeout(()=>t.style.opacity=0,2800);}
function saveSession(){try{if(S.role)localStorage.setItem("knollad_sess",JSON.stringify({role:S.role,cust:S.cust,view:S.view}));}catch(e){}}
function restoreSession(){try{var r=localStorage.getItem("knollad_sess");if(!r)return;var o=JSON.parse(r);if(o.role==="customer"&&o.cust){S.role="customer";S.cust=o.cust;S.view=(o.view&&o.view!=="home")?o.view:"customer-dashboard";}else if(o.role==="admin"){S.role="admin";S.view=(o.view&&o.view!=="home")?o.view:"admin-dashboard";}}catch(e){}}
restoreSession();render();
