function viewApplySuccess(){const sub=S._submitted;
const rows=sub&&sub.channels.length?`<div class="mt-5 space-y-2">${sub.channels.map(x=>`<div class="flex items-center gap-3 bg-g50 rounded-[20px] p-3">${logoEl(x.c,"w-10 h-10 text-base")}<div class="flex-1 text-left"><p class="text-[15px] font-bold text-g900">${esc(x.c.name)}</p><p class="text-[13px] text-g400">${x.p==='production'?'제작+발행':'단순발행'}</p></div><p class="text-[15px] font-bold text-g900 num">${wonM(x.p==='production'?x.c.prod:x.c.pub)}</p></div>`).join("")}<div class="flex justify-between items-center pt-3 px-1"><span class="text-[15px] font-bold text-g600">합계 (VAT 별도)</span><span class="text-[19px] font-bold text-blue num">${wonM(sub.total)}</span></div></div>`:"";
return `<div class="min-h-screen bg-g50 flex items-center justify-center px-6 py-16"><div class="max-w-md w-full fade-up"><div class="${CARD} p-8 text-center">
<div class="w-16 h-16 rounded-full bg-blue-tint flex items-center justify-center mx-auto mb-6"><i data-lucide="check" class="w-8 h-8 text-blue"></i></div>
<h1 class="text-[26px] font-bold text-g900 mb-1.5">신청이 접수되었어요</h1><p class="text-[16px] text-g500">${sub?esc(sub.brand)+' 캠페인':'크놀AD 캠페인'} 신청이 정상 접수되었습니다.</p>
<div class="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-amber-50 mt-4"><span class="w-1.5 h-1.5 rounded-full bg-amber-400"></span><span class="text-[14px] font-bold text-amber-700">검토 대기중</span></div>${rows}
<div class="mt-7 text-left bg-g50 rounded-[20px] p-4 text-[15px] text-g600 leading-relaxed">승인 완료 시 입력하신 이메일(${sub?esc(sub.email):'이메일'})을 아이디로 계정이 발급되고 비밀번호가 안내됩니다. ‘로그인’에서 로그인 후 진행 상태를 확인하세요.</div>
<button onclick="goHome()" class="${BTN_GHOST} w-full mt-5">홈으로 돌아가기</button></div></div></div>`;}

/* ===== 로그인 ===== */
function viewLogin(){return `<div class="min-h-screen bg-g50 flex items-center justify-center px-6"><div class="w-full max-w-sm fade-up">
<div class="text-center mb-8">${logoMark('w-14 h-14 mx-auto mb-3')}<h1 class="text-[24px] font-bold text-g900">로그인</h1><p class="text-[16px] text-g500 mt-1">승인된 고객 / 관리자 전용</p></div>
<div class="${CARD} p-7 space-y-4">${field('아이디 (이메일)',`<input id="loginEmail" type="text" placeholder="name@company.com" class="${INPUT}">`)}${field('비밀번호',`<input id="loginPw" type="password" placeholder="발급받은 비밀번호" class="${INPUT}" onkeydown="if(event.key==='Enter')doLogin()">`)}<button onclick="doLogin()" id="loginBtn" class="${BTN} w-full">로그인</button></div>
<p class="text-center text-[13px] text-g400 mt-4 leading-relaxed">관리자 승인 전에는 로그인할 수 없습니다.<br>승인 후 발급받은 이메일·비밀번호로 로그인하세요.</p><button onclick="goHome()" class="w-full text-center text-[15px] text-g500 hover:text-g800 mt-3">← 홈으로</button></div></div>`;}
function doLogin(){const e=(gv("loginEmail")||"").trim().toLowerCase();const pw=gv("loginPw")||"";
  if(e==="admin"){if(pw==="admin123"){S.role="admin";go("admin-dashboard");}else toast("관리자 비밀번호가 올바르지 않습니다");return;}
  if(!e||!pw){toast("아이디와 비밀번호를 입력해주세요");return;}
  const btn=document.getElementById("loginBtn");if(btn)btn.textContent="확인 중…";
  fetch(SUPA_URL+`/rest/v1/knollad_applications?account_id=eq.${encodeURIComponent(e)}&account_pw=eq.${encodeURIComponent(pw)}&status=eq.${encodeURIComponent("승인 완료")}&select=brand_name,contact_name&limit=1`,{headers:SH})
  .then(r=>r.json()).then(rows=>{if(Array.isArray(rows)&&rows.length){S.role="customer";S.cust={email:e,brand:rows[0].brand_name,name:rows[0].contact_name};S.wf={step:1,edit:null};go("customer-dashboard");}else{if(btn)btn.textContent="로그인";toast("승인된 계정이 아니거나 정보가 일치하지 않습니다");}})
  .catch(()=>{if(btn)btn.textContent="로그인";toast("로그인 오류. 잠시 후 다시 시도해주세요");});}

/* ===== SHELLS ===== */
function sidebar(items,cur,badge){return `<aside class="w-56 border-r border-g100 flex flex-col fixed top-0 bottom-0 z-20 bg-white"><div class="px-5 py-5">${brandLogo(true,true)}${badge?`<span class="mt-2 inline-flex px-2 py-0.5 rounded-md bg-blue-tint text-blue text-[11px] font-bold">${badge}</span>`:""}</div><nav class="flex-1 px-3 space-y-1 overflow-y-auto">${items.map(it=>{const a=cur===it.id;return `<button onclick="${it.act||("go('"+it.id+"')")}" class="w-full flex items-center gap-3 px-3 py-2.5 rounded-2xl text-[15px] font-bold ${a?'bg-blue-tint text-blue':'text-g500 hover:text-g800 hover:bg-g100'}"><i data-lucide="${it.icon}" class="w-[16px] h-[16px]"></i>${it.label}</button>`;}).join("")}</nav><div class="px-3 py-3 border-t border-g100"><button onclick="logout()" class="w-full flex items-center gap-3 px-3 py-2.5 rounded-2xl text-[15px] font-bold text-g500 hover:text-g800 hover:bg-g100"><i data-lucide="log-out" class="w-[16px] h-[16px]"></i>로그아웃</button></div></aside>`;}
function customerShell(v){const items=[{id:"customer-dashboard",label:"캠페인 관리",icon:"layout-dashboard"},{id:"cust-channels",label:"채널 리스트",icon:"layers"},{id:"cust-apply",label:"캠페인 추가 신청",icon:"plus-circle",act:"newApply()"},{id:"workflow",label:"워크플로우",icon:"git-branch"},{id:"settlement",label:"정산",icon:"receipt"},{id:"mypage",label:"마이페이지",icon:"user"},{id:"report",label:"리포트",icon:"bar-chart-3"}];
let b;if(v==="cust-channels")b=custChannels();else if(v==="cust-apply")b=custApply();else if(v==="workflow")b=viewWorkflow();else if(v==="settlement")b=viewSettlement();else if(v==="mypage")b=viewMyPage();else if(v==="report")b=viewReport();else b=viewCustomerDashboard();
return `<div class="flex min-h-screen bg-g50">${sidebar(items,v)}<main class="flex-1 ml-56 min-h-screen">${b}</main></div>`;}
function adminShell(v){const items=[{id:"admin-dashboard",label:"캠페인 관리",icon:"clipboard-list"},{id:"admin-members",label:"회원DB",icon:"users"},{id:"admin-channels",label:"채널 DB",icon:"layers"}];let b=v==="admin-members"?viewAdminMembers():v==="admin-channels"?viewAdminChannels():viewAdminList();return `<div class="flex min-h-screen bg-g50">${sidebar(items,v,"관리자")}<main class="flex-1 ml-56 min-h-screen">${b}</main></div>`;}

/* ===== CUSTOMER ===== */
function custChannels(){return `<div class="p-8 md:p-10">
<div class="flex items-center justify-between mb-6 flex-wrap gap-3"><div><p class="text-[15px] font-bold text-blue mb-2">CHANNELS</p><h1 class="text-[32px] font-bold text-g900 tracking-tight">채널 리스트</h1><p class="text-[16px] text-g500 mt-2">원하는 채널을 체크하면 ‘캠페인 추가 신청’에 반영됩니다</p></div><button onclick="go('cust-apply')" class="${BTN} px-6">선택 완료 <span id="selCnt">${SEL.size}</span> →</button></div>
${channelTableBlock()}</div>`;}
function custApply(){return `<div class="p-8 md:p-10"><div class="max-w-2xl">${pageHeader("CAMPAIGN","캠페인 추가 신청","새 캠페인을 신청하면 동일하게 검토 후 진행됩니다")}
<div class="${CARD} p-6 md:p-8">${NOTICE}${applyFields()}<button onclick="submitApply()" class="${BTN} w-full py-4 mt-6">추가 캠페인 신청하기</button></div></div></div>`;}
const WF=[
{t:"문의 접수 및 상담",d:"단가·일정 안내 및 채널·제작 방향 협의",who:"완료"},
{t:"자료 공유",d:"소재·가이드·레퍼런스 전달 (고객 → 크놀AD)",who:"고객",act:"data"},
{t:"콘티 작성",d:"전달받은 자료로 콘티(기획안) 작성 (크놀AD)",who:"크놀AD",act:"work"},
{t:"콘티 컨펌 및 피드백",d:"콘티 검토 후 컨펌 또는 수정 요청 (고객)",who:"고객",act:"conti"},
{t:"영상 제작",d:"확정 콘티로 촬영·편집 (크놀AD)",who:"크놀AD",act:"work"},
{t:"영상 컨펌 및 피드백",d:"영상 검토 후 컨펌 또는 수정 요청 (고객)",who:"고객",act:"video"},
{t:"업로드 & URL 전달",d:"YouTube·IG·TikTok 발행, 멘션 적용, URL 전달 (크놀AD)",who:"크놀AD",act:"upload"},
{t:"인사이트 리포트",d:"도달·조회수 등 성과 리포트 제공 (크놀AD)",who:"크놀AD",act:"report"}];
function loadMyCamps(){if(!S.cust)return;fetch(SUPA_URL+"/rest/v1/knollad_applications?email=eq."+encodeURIComponent(S.cust.email)+"&order=created_at.desc&select=*",{headers:SH}).then(r=>r.json()).then(rows=>{S.myCamps=Array.isArray(rows)?rows:[];renderMyCamps();}).catch(()=>{});}
function renderMyCamps(){const el=document.getElementById("myCampWrap");if(!el)return;const cs=S.myCamps||[];if(!cs.length){el.innerHTML='<div class="text-[15px] text-g400 text-center py-8">아직 신청한 캠페인이 없습니다.<br>상단 ‘캠페인 추가 신청’으로 시작하세요.</div>';return;}
el.innerHTML=cs.map(a=>`<div class="border border-g100 rounded-[20px] p-4 flex items-center gap-3 flex-wrap"><div class="flex-1 min-w-0"><div class="flex items-center gap-2"><p class="font-bold text-g900 text-[16px] truncate">${esc(a.brand_name)}</p>${statusBadge(a.status)}</div><p class="text-[13px] text-g500 mt-1 truncate">${(a.channels||[]).map(c=>c.name).join(", ")||"채널 미선택"}</p></div><div class="text-right flex-shrink-0"><p class="text-[16px] font-bold text-blue num">${wonM(a.total_amount||0)}</p><p class="text-[12px] text-g400 num">${(a.created_at||"").slice(0,10)}</p></div></div>`).join("");}
function viewCustomerDashboard(){setTimeout(loadMyCamps,30);const cur=S.wf.step;const bn=(S.cust&&S.cust.brand)?S.cust.brand:"고객";const pct=Math.round(cur/8*100);
const todo={1:["소재·가이드 파일 업로드","참고 레퍼런스 제출"],3:["콘티 확인 후 컨펌 또는 수정 요청"],5:["영상 확인 후 컨펌 또는 수정 요청"],6:["업로드 URL 확인"],7:["인사이트 리포트 확인"]}[cur]||["크놀AD 작업 대기 중"];
const steps=WF.map((s,i)=>{const done=i<cur,act=i===cur;return `<div class="flex items-center gap-3 px-3 py-2.5 rounded-2xl ${act?'bg-blue-tint':''}"><div class="w-6 h-6 rounded-full grid place-items-center flex-shrink-0 text-[12px] font-bold ${done?'bg-emerald-500 text-white':act?'bg-blue text-white':'bg-g200 text-g500'}">${done?'<i data-lucide="check" class="w-3 h-3"></i>':i+1}</div><span class="text-[15px] flex-1 ${done?'text-g400 line-through':act?'text-g900 font-bold':'text-g500'}">${s.t}</span>${done?'<span class="text-[13px] text-emerald-600 font-bold">완료</span>':act?'<span class="text-[13px] text-blue font-bold">진행중</span>':'<span class="text-[13px] text-g300">대기</span>'}</div>`;}).join("");
return `<div class="p-8 md:p-10">${pageHeader("CAMPAIGN","캠페인 관리",esc(bn)+" 님의 캠페인 현황입니다.")}
<div class="grid lg:grid-cols-3 gap-4 mb-4"><div class="${CARD} lg:col-span-2 p-7"><div class="flex items-center justify-between mb-4"><h2 class="text-[18px] font-bold text-g900">내 캠페인</h2><button onclick="newApply()" class="text-[14px] text-blue font-bold inline-flex items-center gap-1"><i data-lucide="plus" class="w-4 h-4"></i>캠페인 추가 신청</button></div><div id="myCampWrap" class="space-y-2"><div class="text-g400 text-center py-8 text-[15px]">불러오는 중…</div></div></div>
<div class="${CARD} p-7 flex flex-col items-center justify-center text-center"><p class="text-[14px] text-g400 mb-1">진행 단계</p><div class="font-display text-[48px] font-bold text-g900 num leading-none">${cur}<span class="text-[24px] text-g300">/8</span></div><p class="text-[13px] text-g500 mb-3">${WF[cur]?esc(WF[cur].t):"완료"}</p><div class="w-full bg-g100 rounded-full h-2 mb-3"><div class="bg-blue h-2 rounded-full transition-all" style="width:${pct}%"></div></div><button onclick="go('workflow')" class="text-[15px] text-blue font-bold">워크플로우 진행하기 →</button></div></div>
<div class="grid lg:grid-cols-2 gap-4"><div class="${CARD} p-7"><h2 class="text-[16px] font-bold text-g900 mb-4">진행 단계</h2><div class="space-y-0.5">${steps}</div></div><div class="${CARD} p-7"><h2 class="text-[16px] font-bold text-g900 mb-3">현재 할 일</h2>${todo.map(it=>`<div class="flex items-center gap-3 py-1.5"><div class="w-2 h-2 rounded-full bg-blue flex-shrink-0"></div><span class="text-[16px] text-g700">${it}</span></div>`).join("")}<button onclick="go('workflow')" class="${BTN} w-full mt-4 py-3">워크플로우에서 처리하기</button></div></div></div>`;}
function viewMyPage(){const c=S.cust||{};const kv=(k,v)=>`<div class="flex justify-between py-2 border-b border-g100 last:border-0"><span class="text-g500 text-[15px]">${k}</span><span class="font-bold text-g900 text-[15px] text-right break-all">${esc(v||'-')}</span></div>`;
return `<div class="p-8 md:p-10"><div class="max-w-2xl">${pageHeader("MY PAGE","마이페이지","내 정보와 서류(사업자등록증·통장 사본·세금계산서)를 관리합니다")}
<div class="${CARD} p-7 mb-4"><h2 class="text-[16px] font-bold text-g900 mb-3">내 정보</h2>${kv("담당자",c.name)}${kv("아이디(이메일)",c.email)}${kv("회사/브랜드",c.brand)}</div>
<div class="${CARD} p-7 mb-4"><h2 class="text-[16px] font-bold text-g900 mb-3">사업자등록증</h2>${uploadZone("bizFile","사업자등록증 이미지 또는 PDF")}</div>
<div class="${CARD} p-7 mb-4"><h2 class="text-[16px] font-bold text-g900 mb-3">통장 사본 (표지)</h2>${uploadZone("bankFile","통장 표지 이미지 또는 PDF")}</div>
<div class="${CARD} p-7"><h2 class="text-[16px] font-bold text-g900 mb-3">세금계산서</h2><div class="flex items-center justify-between bg-g50 rounded-2xl p-3"><div><p class="font-bold text-g900 text-[15px]">발행 내역</p><p class="text-[13px] text-g400">업로드 완료·정산 시 발행된 세금계산서가 표시됩니다.</p></div><button onclick="toast('데모: 발행 내역')" class="text-[13px] text-blue font-bold">보기</button></div></div>
<button onclick="toast('서류가 제출되었습니다')" class="${BTN} w-full mt-4">서류 제출</button>
</div></div>`;}
function uploadZone(id,hint){id=id||"fileList";return `<label class="block border-2 border-dashed border-g300 rounded-[20px] p-7 text-center cursor-pointer hover:border-blue hover:bg-blue-soft transition-all"><input type="file" multiple class="hidden" onchange="showFiles(this,'${id}')"><i data-lucide="upload-cloud" class="w-9 h-9 text-g400 mx-auto mb-2"></i><p class="text-[17px] font-bold text-g700">파일을 끌어다 놓거나 클릭해서 업로드</p><p class="text-[14px] text-g400 mt-1">${hint||"제품 이미지·영상·로고·가이드 등 (여러 개 가능)"}</p></label><div id="${id}" class="space-y-2 mt-3"></div>`;}
function showFiles(input,id){const el=document.getElementById(id||"fileList");if(!el)return;const fs=[...input.files];el.innerHTML=fs.map(f=>`<div class="flex items-center gap-2 bg-g50 rounded-2xl px-3 py-2 text-[15px]"><i data-lucide="file" class="w-4 h-4 text-blue flex-shrink-0"></i><span class="flex-1 truncate text-g700">${esc(f.name)}</span><span class="text-g400 text-[12px] num">${(f.size/1024).toFixed(0)}KB</span></div>`).join("");if(window.lucide)lucide.createIcons();if(fs.length)toast(fs.length+"개 파일 선택됨");}
function wfNext(){S.wf.edit=null;if(S.wf.step<8){S.wf.step++;toast(S.wf.step>=8?"모든 단계를 완료했습니다":"다음 단계로 진행되었습니다");}render();}
function wfReqEdit(){const t=(gv("wfFb")||"").trim();S.wf.edit={stage:S.wf.step,note:t};toast("수정 요청이 전달되었습니다 · 크놀AD가 반영 후 재전달합니다");render();}
function wfPanel(s){const act=s.act,P='class="mt-4 space-y-3" style="padding-left:52px"';
if(act==="data")return `<div ${P}>${uploadZone()}<input id="wfRef" placeholder="참고 레퍼런스 / 소재 링크 (선택)" class="${INPUT}"><button onclick="wfNext()" class="${BTN} w-full">자료 제출 완료 →</button></div>`;
if(act==="work")return `<div ${P}><div class="bg-g50 rounded-2xl p-4 text-[15px] text-g600 flex items-center gap-3"><i data-lucide="loader-circle" class="w-5 h-5 text-blue"></i>크놀AD에서 ${s.t} 작업 중입니다. 완료되면 알림과 함께 전달됩니다.</div><button onclick="wfNext()" class="${BTN_GHOST} text-[14px] py-2.5 px-5">전달 받기 (데모) →</button></div>`;
if(act==="conti"||act==="video"){const label=act==="conti"?"콘티":"영상 초안";const edited=S.wf.edit&&S.wf.edit.stage===S.wf.step;return `<div ${P}><div class="bg-blue-soft rounded-2xl p-4"><p class="font-bold text-g900 mb-1">${label}가 전달되었습니다</p><button onclick="toast('데모: 실제 운영 시 파일/링크가 열립니다')" class="text-blue font-bold text-[14px] inline-flex items-center gap-1"><i data-lucide="paperclip" class="w-4 h-4"></i>${label} 확인하기</button>${edited?`<p class="text-[13px] text-orange-600 font-bold mt-2">수정 요청 전달됨 — 크놀AD 재전달 대기 중</p>`:''}</div><textarea id="wfFb" rows="2" placeholder="수정 요청 사항을 입력하세요 (선택)" class="${INPUT} resize-none"></textarea><div class="flex gap-2"><button onclick="wfReqEdit()" class="${BTN_GHOST} flex-1">수정 요청</button><button onclick="wfNext()" class="${BTN} flex-1">컨펌하고 다음 →</button></div></div>`;}
if(act==="upload")return `<div ${P}><div class="bg-g50 rounded-2xl p-4 space-y-2"><p class="font-bold text-g900">업로드 완료 · URL</p>${[["YouTube","text-red-500"],["Instagram","text-pink-500"],["TikTok","text-g800"]].map(p=>`<div class="flex items-center gap-2 text-[14px]"><span class="font-bold ${p[1]} w-20">${p[0]}</span><button onclick="toast('데모 업로드 URL')" class="text-blue">업로드 링크 보기 ↗</button></div>`).join("")}<p class="text-[13px] text-g500 pt-1">멘션·해시태그 적용 완료 · IG/TikTok 미러링 발행 완료</p></div><button onclick="wfNext()" class="${BTN} w-full">확인 →</button></div>`;
if(act==="report")return `<div ${P}><div class="bg-g50 rounded-2xl p-4 text-[15px] text-g600">업로드 이후 72시간 내 도달·조회수·인게이지먼트 리포트가 제공됩니다. <span class="text-amber-700 font-bold">조회수 수집중</span></div></div>`;
return "";}
function viewWorkflow(){const cur=S.wf.step;
const cards=WF.map((s,i)=>{const done=i<cur,act=i===cur;return `<div class="${CARD} p-5 ${act?'border-2 border-blue':''}"><div class="flex items-center gap-4"><div class="w-9 h-9 rounded-full grid place-items-center flex-shrink-0 font-bold text-[14px] ${done?'bg-emerald-500 text-white':act?'bg-blue text-white':'bg-g100 text-g400'}">${done?'<i data-lucide="check" class="w-4 h-4"></i>':String(i+1).padStart(2,"0")}</div><div class="flex-1"><p class="font-bold text-[16px] ${done?'text-g400':act?'text-g900':'text-g400'}">${s.t}</p><p class="text-[13px] text-g400 mt-0.5">${s.d}</p></div><span class="text-[12px] font-bold px-2.5 py-1 rounded-lg ${act?'bg-blue-tint text-blue':done?'bg-emerald-50 text-emerald-600':'bg-g100 text-g400'}">${done?'완료':act?'진행중':s.who}</span></div>${act?wfPanel(s):''}</div>`;}).join("");
const policy=[["콘티 수정","2회까지 무상수정 · 3회차부터 추가요금"],["영상 수정","단순 컷·순서·로고 변경 한정 2회 무상 · 3회차부터 추가요금"],["콘티 변경 발생 시","무상수정 횟수와 관계없이 추가요금 발생"],["제작사 실수로 인한 오류","횟수 제한 없이 무상수정 진행"]];
return `<div class="p-8 md:p-10">${pageHeader("WORKFLOW","캠페인 진행","신청부터 자료 제출·콘티/영상 컨펌·업로드·정산까지 홈페이지 안에서 진행됩니다")}
<div class="grid lg:grid-cols-3 gap-5"><div class="lg:col-span-2 space-y-3">${cards}</div>
<div class="${CARD} p-6 self-start lg:sticky lg:top-6"><h2 class="text-[16px] font-bold text-g900 mb-4">수정 정책 및 추가요금</h2><div class="space-y-3">${policy.map(p=>`<div class="pb-3 border-b border-g100 last:border-0 last:pb-0"><p class="font-bold text-[15px] text-g900 mb-1">${p[0]}</p><p class="text-[15px] text-g500 leading-relaxed">${p[1]}</p></div>`).join("")}</div><button onclick="go('settlement')" class="${BTN_GHOST} w-full mt-4 py-3 text-[14px]">정산 단계로 →</button></div></div></div>`;}
function viewSettlement(){return `<div class="p-8 md:p-10"><div class="max-w-2xl">${pageHeader("SETTLEMENT","정산","업로드 완료 후 세금계산서 발행을 위한 정보를 제출하세요")}
<div class="${CARD} p-7 space-y-4"><div class="bg-blue-soft rounded-2xl p-4 text-[14px] text-g700 leading-relaxed">세금계산서 발행 및 정산을 위해 <b>사업자등록증·통장사본</b>을 업로드하고 발행 정보를 입력해주세요. (단가는 VAT 별도 기준)</div>
${field('사업자등록증 / 통장사본 업로드',uploadZone())}
<div class="grid grid-cols-2 gap-3">${field('상호 / 사업자명',`<input class="${INPUT}" placeholder="사업자명">`)}${field('사업자등록번호',`<input class="${INPUT}" placeholder="000-00-00000">`)}</div>
<div class="grid grid-cols-2 gap-3">${field('발행 이메일',`<input class="${INPUT}" placeholder="tax@company.com">`)}${field('입금 예정일',`<input type="date" class="${INPUT}">`)}</div>
${field('비고 (공급가액·항목 등)',`<textarea rows="2" class="${INPUT} resize-none" placeholder="예: (쇼잉) 750,000 / (두근두근) 650,000 ... 공급가액 기준, VAT 별도"></textarea>`)}
<button onclick="toast('정산 정보가 제출되었습니다')" class="${BTN} w-full">정산 정보 제출</button></div></div></div>`;}
function viewReport(){const ready=S.wf.step>=7;return `<div class="p-8 md:p-10">${pageHeader("REPORT","인사이트 리포트")}<div class="max-w-xl">${ready?`<div class="grid grid-cols-3 gap-3 mb-4">${[["조회수","128,400"],["도달","96,200"],["좋아요","4,180"]].map(x=>`<div class="${CARD} p-5 text-center"><p class="text-[13px] text-g400 mb-1">${x[0]}</p><p class="text-[24px] font-bold text-g900 num">${x[1]}</p></div>`).join("")}</div><div class="${CARD} p-6 text-[15px] text-g600">* 데모 수치입니다. 실제 운영 시 채널 인사이트(API/수기 집계)로 연동됩니다.</div>`:`<div class="${CARD} p-14 text-center"><div class="w-14 h-14 rounded-[20px] bg-g100 grid place-items-center mx-auto mb-5"><i data-lucide="bar-chart-3" class="w-7 h-7 text-g300"></i></div><p class="text-[18px] font-bold text-g900 mb-1.5">업로드 완료 후 리포트가 제공됩니다</p><p class="text-[16px] text-g500 mb-5">업로드 이후 72시간 이내 인사이트 데이터가 수집됩니다.</p><div class="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-amber-50"><i data-lucide="clock" class="w-3.5 h-3.5 text-amber-600"></i><span class="text-[15px] font-bold text-amber-700">조회수 수집중</span></div></div>`}</div></div>`;}

/* ===== ADMIN ===== */
function genPw(){return "kn"+Math.random().toString(36).slice(2,7)+Math.floor(Math.random()*90+10);}
function loadApps(){fetch(SUPA_URL+"/rest/v1/knollad_applications?select=*&order=created_at.desc",{headers:SH}).then(r=>r.json()).then(rows=>{ADM_ROWS=Array.isArray(rows)?rows:[];if(S.view==="admin-dashboard")renderAdmRows();else if(S.view==="admin-members")renderMembers();}).catch(()=>{const b=document.getElementById("admRows");if(b)b.innerHTML='<tr><td colspan="8" class="px-4 py-10 text-center text-g400">불러오기 실패</td></tr>';});}
function viewAdminList(){setTimeout(loadApps,30);return `<div class="p-8 md:p-10">${pageHeader("ADMIN","캠페인 관리","폼으로 접수된 실제 신청 데이터 · 승인 시 계정 자동 발급")}
<div class="grid grid-cols-2 md:grid-cols-4 gap-3 mb-6" id="admStats"></div>
<div class="${CARD} overflow-hidden"><div class="overflow-x-auto"><table class="w-full text-left min-w-[960px]"><thead><tr class="border-b border-g100 bg-g50">${["접수일","브랜드","담당자","이메일","연락처","채널 / 금액","상태","처리"].map(h=>`<th class="px-4 py-3 text-[13px] font-bold text-g500 whitespace-nowrap">${h}</th>`).join("")}</tr></thead><tbody id="admRows"><tr><td colspan="8" class="px-4 py-10 text-center text-g400">불러오는 중…</td></tr></tbody></table></div></div></div>`;}
function renderAdmRows(){const b=document.getElementById("admRows");if(!b)return;const rows=ADM_ROWS;
b.innerHTML=rows.length?rows.map(a=>{const chans=(a.channels||[]).map(c=>c.name).join(", ")||"-";const approved=a.status==="승인 완료";return `<tr class="border-b border-g100 last:border-0 hover:bg-g50 align-top"><td class="px-4 py-3 text-[13px] text-g400 num">${(a.created_at||"").slice(0,10)}</td><td class="px-4 py-3 font-bold text-g900 text-[15px]">${esc(a.brand_name)}</td><td class="px-4 py-3 text-g700 text-[15px]">${esc(a.contact_name)}</td><td class="px-4 py-3 text-g500 text-[14px]">${esc(a.email)}</td><td class="px-4 py-3 text-g500 text-[14px] num">${esc(a.phone)}</td><td class="px-4 py-3 text-[14px] max-w-[220px]"><div class="text-g700 truncate">${esc(chans)}</div><div class="text-blue font-bold num">${wonM(a.total_amount||0)}</div></td><td class="px-4 py-3">${statusBadge(a.status)}${approved&&a.account_pw?`<button onclick="showCreds('${esc(a.account_id||a.email)}','${esc(a.account_pw)}')" class="block mt-1 text-[12px] text-blue font-bold">계정/안내문</button>`:''}</td><td class="px-4 py-3"><div class="flex gap-1">${approved?'':`<button onclick="admApprove('${a.id}','${esc(a.email)}')" class="px-2.5 py-1.5 rounded-xl bg-blue text-white text-[12px] font-bold">승인</button>`}<button onclick="admUpdate('${a.id}','진행중')" class="px-2.5 py-1.5 rounded-xl bg-g100 text-g700 text-[12px] font-bold">진행</button><button onclick="admUpdate('${a.id}','반려')" class="px-2.5 py-1.5 rounded-xl bg-red-50 text-red-600 text-[12px] font-bold">반려</button></div></td></tr>`;}).join(""):'<tr><td colspan="8" class="px-4 py-10 text-center text-g400">아직 접수된 신청이 없습니다. 폼에서 신청하면 여기에 표시됩니다.</td></tr>';
const s=document.getElementById("admStats");if(s){const c=k=>rows.filter(a=>a.status===k).length;s.innerHTML=[["전체 신청",rows.length],["검토 대기",c("검토 대기중")],["승인 완료",c("승인 완료")],["진행중",c("진행중")]].map(x=>`<div class="${CARD} p-5"><p class="text-[14px] text-g400 mb-1.5">${x[0]}</p><p class="font-display text-[30px] font-bold text-g900 num">${x[1]}</p></div>`).join("");}}
function admApprove(id,email){const pw=genPw();fetch(SUPA_URL+"/rest/v1/knollad_applications?id=eq."+id,{method:"PATCH",headers:Object.assign({"Content-Type":"application/json","Prefer":"return=minimal"},SH),body:JSON.stringify({status:"승인 완료",account_id:email,account_pw:pw,approved_at:new Date().toISOString()})}).then(r=>{if(r.ok){loadApps();showCreds(email,pw);}else toast("승인 실패 (권한)");}).catch(()=>toast("승인 실패"));}
function admUpdate(id,status){fetch(SUPA_URL+"/rest/v1/knollad_applications?id=eq."+id,{method:"PATCH",headers:Object.assign({"Content-Type":"application/json","Prefer":"return=minimal"},SH),body:JSON.stringify({status})}).then(r=>{if(r.ok){toast(status+" 처리됨");loadApps();}else toast("처리 실패");}).catch(()=>toast("처리 실패"));}
function showCreds(email,pw){CRED_MSG="[크놀AD] 캠페인 신청이 승인되었습니다.\n\n■ 로그인 정보\n- 아이디(이메일): "+email+"\n- 비밀번호: "+pw+"\n- 로그인: https://cnolad.vercel.app  (로그인)\n\n승인된 계정으로 로그인하시면 채널 선택, 단가 확인, 자료 업로드, 컨펌, 업로드 일정, 리포트까지 실시간으로 확인하실 수 있습니다.\n감사합니다. 에이치알컴퍼니(주) 드림";
modal(`<div class="text-center"><div class="w-14 h-14 rounded-full bg-blue-tint grid place-items-center mx-auto mb-4"><i data-lucide="key-round" class="w-7 h-7 text-blue"></i></div><h3 class="text-[20px] font-bold text-g900 mb-1">계정 발급 완료</h3><p class="text-g500 text-[14px] mb-4">아래 안내문을 복사해 고객에게 전달하세요.</p></div>
<div class="bg-g50 rounded-[20px] p-4 space-y-2 text-[15px] mb-3"><div class="flex justify-between gap-3"><span class="text-g500">아이디</span><span class="font-bold text-g900 break-all text-right">${esc(email)}</span></div><div class="flex justify-between gap-3"><span class="text-g500">비밀번호</span><span class="font-bold text-blue num">${esc(pw)}</span></div></div>
<div class="bg-blue-soft rounded-[20px] p-4 text-[13px] text-g700 whitespace-pre-line max-h-40 overflow-y-auto mb-3">${esc(CRED_MSG)}</div>
<div class="flex gap-2"><button onclick="copyText(CRED_MSG)" class="${BTN} flex-1"><i data-lucide="copy" class="w-4 h-4"></i>승인 안내문 복사</button><button onclick="closeModal()" class="${BTN_GHOST} px-5">닫기</button></div>`);}
function memberCampaigns(email){const rows=ADM_ROWS.filter(a=>a.email===email);const items=rows.map(a=>`<div class="flex items-center justify-between gap-3 bg-g50 rounded-2xl p-3"><div class="min-w-0"><p class="font-bold text-g900">${esc(a.brand_name)}</p><p class="text-[12px] text-g400 truncate">${(a.created_at||"").slice(0,10)} · ${(a.channels||[]).map(c=>c.name).join(", ")||"-"} · ${wonM(a.total_amount||0)}</p></div>${statusBadge(a.status)}</div>`).join("");modal(`<div class="flex items-center justify-between mb-1"><h3 class="text-[19px] font-bold text-g900 break-all">${esc(email)}</h3><button onclick="closeModal()" class="w-8 h-8 rounded-full bg-g100 grid place-items-center text-g500 flex-shrink-0">✕</button></div><p class="text-[14px] text-g500 mb-4">신청 ${rows.length}건</p><div class="space-y-2 max-h-[55vh] overflow-y-auto">${items||'<p class="text-g400 text-center py-6">신청 내역이 없습니다.</p>'}</div><button onclick="closeModal()" class="${BTN} w-full mt-4">닫기</button>`);}
function addChannelByHandle(){const el=document.getElementById("newHandle");let h=((el?el.value:"")||"").trim().replace(/^@/,"");if(!h){toast("핸들을 입력해주세요");return;}toast("채널 정보를 불러오는 중…");fetch("https://www.googleapis.com/youtube/v3/channels?part=snippet,statistics&forHandle="+encodeURIComponent(h)+"&fields=items(id,snippet/title,snippet/thumbnails/medium/url,statistics/subscriberCount,statistics/viewCount,statistics/videoCount)&key="+YT_API_KEY).then(r=>r.json()).then(res=>{const it=(res.items||[])[0];if(!it){toast("채널을 찾을 수 없습니다");return;}if(CH.find(c=>c.id===it.id)){toast("이미 등록된 채널입니다");return;}const st=it.statistics||{},sn=it.snippet||{};CH.push({id:it.id,name:sn.title||h,read:null,region:"KR",plat:["YouTube"],handle:h,yt:+st.subscriberCount||0,views:+st.viewCount||0,vids:+st.videoCount||0,ig:null,tt:null,prod:65,pub:30,logo:(sn.thumbnails&&sn.thumbnails.medium)?sn.thumbnails.medium.url:null});toast("추가됨: "+(sn.title||h));render();}).catch(()=>toast("불러오기 실패"));}
function viewAdminChannels(){return `<div class="p-8 md:p-10">${pageHeader("CHANNEL DB","채널 관리",`총 ${CH.length}개 채널 · 핸들로 채널을 추가할 수 있습니다`)}<div class="${CARD} p-5 mb-4 flex items-center gap-3 flex-wrap"><div class="flex-1 min-w-[220px]"><input id="newHandle" placeholder="유튜브 핸들 입력 (예: mimtube777)" class="${INPUT}" onkeydown="if(event.key==='Enter')addChannelByHandle()"></div><button onclick="addChannelByHandle()" class="${BTN} px-6"><i data-lucide="plus" class="w-4 h-4"></i>채널 추가</button></div><div class="${CARD} overflow-hidden"><div class="overflow-x-auto"><table class="w-full text-[14px] min-w-[820px]"><thead><tr class="border-b border-g100 bg-g50">${["채널","플랫폼","구독자(YT)","총 조회수","평균","제작+발행","단순발행","공개"].map(h=>`<th class="px-5 py-3.5 text-left text-[13px] font-bold text-g500 whitespace-nowrap">${h}</th>`).join("")}</tr></thead><tbody>${CH.map(c=>`<tr class="border-b border-g100 last:border-0 hover:bg-g50"><td class="px-5 py-3"><div class="flex items-center gap-3">${logoEl(c,"w-8 h-8 text-sm")}<div><p class="font-bold text-g900">${esc(c.name)}</p><p class="text-[13px] text-g400">${REGION_LABEL[c.region]}${c.read?" · "+esc(c.read):""}</p></div></div></td><td class="px-5 py-3"><div class="flex gap-1 flex-wrap">${c.plat.map(platBadge).join("")}</div></td><td class="px-5 py-3 text-g600 num">${fmtSub(c.yt)}</td><td class="px-5 py-3 text-g600 num">${fmtView(c.views)}</td><td class="px-5 py-3 text-g600 num">${fmtView(avgView(c))}</td><td class="px-5 py-3 font-bold text-g900 num">${c.prod}만</td><td class="px-5 py-3 font-bold text-g900 num">${c.pub}만</td><td class="px-5 py-3"><button onclick="this.querySelector('span').classList.toggle('translate-x-[18px]');this.classList.toggle('bg-blue');this.classList.toggle('bg-g300')" class="relative inline-flex h-5 w-9 items-center rounded-full bg-blue transition-colors"><span class="inline-block w-3.5 h-3.5 rounded-full bg-white shadow-sm transform transition-transform translate-x-[18px]"></span></button></td></tr>`).join("")}</tbody></table></div></div></div>`;}
function viewAdminMembers(){setTimeout(loadApps,30);return `<div class="p-8 md:p-10">${pageHeader("MEMBER DB","회원DB","회사/브랜드별 신청 고객 · 행을 클릭하면 캠페인 내역을 볼 수 있습니다")}
<div class="${CARD} overflow-hidden"><div class="overflow-x-auto"><table class="w-full text-left min-w-[860px]"><thead><tr class="border-b border-g100 bg-g50">${["담당자","아이디(이메일)","회사/브랜드","연락처","신청 건수","상태","계정"].map(h=>`<th class="px-4 py-3 text-[13px] font-bold text-g500 whitespace-nowrap">${h}</th>`).join("")}</tr></thead><tbody id="memRows"><tr><td colspan="7" class="px-4 py-10 text-center text-g400">불러오는 중…</td></tr></tbody></table></div></div></div>`;}
function renderMembers(){const b=document.getElementById("memRows");if(!b)return;const map={};ADM_ROWS.forEach(a=>{const k=a.email;if(!map[k])map[k]={name:a.contact_name,email:a.email,phone:a.phone,brand:a.brand_name,count:0,last:a.status,pw:a.account_pw};map[k].count++;map[k].brand=a.brand_name;if(a.account_pw)map[k].pw=a.account_pw;if(a.status==="승인 완료")map[k].last="승인 완료";});const list=Object.values(map);
b.innerHTML=list.length?list.map(m=>`<tr class="border-b border-g100 last:border-0 hover:bg-g50 cursor-pointer" onclick="memberCampaigns('${esc(m.email)}')"><td class="px-4 py-3 font-bold text-g900 text-[15px]">${esc(m.name)}</td><td class="px-4 py-3 text-g600 text-[14px]">${esc(m.email)}</td><td class="px-4 py-3 text-g700 text-[14px] font-bold">${esc(m.brand)}</td><td class="px-4 py-3 text-g600 num text-[14px]">${esc(m.phone)}</td><td class="px-4 py-3 num text-[14px]">${m.count}건</td><td class="px-4 py-3">${statusBadge(m.last)}</td><td class="px-4 py-3">${m.pw?`<button onclick="event.stopPropagation();showCreds('${esc(m.email)}','${esc(m.pw)}')" class="text-[13px] text-blue font-bold">안내문 복사</button>`:'<span class="text-g300 text-[13px]">미발급</span>'}</td></tr>`).join(""):'<tr><td colspan="7" class="px-4 py-10 text-center text-g400">회원이 없습니다.</td></tr>';}

/* ===== LIVE ===== */
let _liveDone=false,_liveTried=false;
function maybeLiveRefresh(){
  if(_liveDone||_liveTried)return;_liveTried=true;
  const ids=CH.map(c=>c.id);
  fetch(`https://www.googleapis.com/youtube/v3/channels?part=snippet,statistics&id=${ids.join(",")}&fields=items(id,snippet/thumbnails/medium/url,statistics/subscriberCount,statistics/viewCount,statistics/videoCount)&key=${YT_API_KEY}`)
  .then(r=>r.json()).then(res=>{(res.items||[]).forEach(it=>{const c=CH.find(x=>x.id===it.id);if(!c)return;if(it.snippet&&it.snippet.thumbnails&&it.snippet.thumbnails.medium)c.logo=it.snippet.thumbnails.medium.url;if(it.statistics){c.yt=+it.statistics.subscriberCount;c.views=+it.statistics.viewCount;c.vids=+it.statistics.videoCount;}});
    _liveDone=true;
    if(S.view==="channel-picker"||S.view==="cust-channels")updateTable();
    else if(document.getElementById("selBox")){document.getElementById("selBox").innerHTML=SEL.size?selectedSummary():'';if(window.lucide)lucide.createIcons();}
  }).catch(()=>{_liveTried=false;});
}
function toast(msg){let t=document.getElementById("toast");if(!t){t=document.createElement("div");t.id="toast";t.className="fixed bottom-8 left-1/2 z-[400] px-5 py-3 rounded-[20px] bg-g900 text-white text-[15px] font-bold shadow-pop transition-all";t.style.opacity=0;document.body.appendChild(t);}t.textContent=msg;t.style.transform="translateX(-50%) translateY(0)";t.style.opacity=1;clearTimeout(t._t);t._t=setTimeout(()=>t.style.opacity=0,2800);}
render();
